from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class SystemStatusResponse(BaseModel):
    api_status: str = Field(..., description="Status of the API service")
    database_status: str = Field(..., description="Status of the database connection")
    # Add more system health indicators as needed
    timestamp: datetime = Field(..., description="Time when the status was checked")


class AnalysisStatus(BaseModel):
    id: UUID = Field(..., description="Unique identifier of the analysis")
    project_id: UUID = Field(..., description="Project ID associated with the analysis")
    status: str = Field(..., description="Current status of the analysis (e.g., COMPLETED, ERROR)")
    coherence_score: int | None = Field(None, description="Coherence score if analysis completed")
    alerts_count: int = Field(..., description="Number of alerts generated by the analysis")
    started_at: datetime = Field(..., description="Timestamp when the analysis started")
    completed_at: datetime | None = Field(None, description="Timestamp when the analysis completed")


class RecentAnalysesResponse(BaseModel):
    analyses: list[AnalysisStatus] = Field(..., description="List of recent coherence analyses")
    total_analyses: int = Field(..., description="Total count of all analyses")
