"""
state.py — LangGraph State Definitions for Coherence Engine v0.3

Defines the state dataclasses used throughout the coherence evaluation subgraph:
- ClauseWithEmbedding: Clause enriched with embedding vector
- CoherenceGraphState: Full state passed between graph nodes

The state follows LangGraph conventions with TypedDict-style annotations
for reducer functions on list fields.

Location: apps/api/src/coherence/graph/state.py
"""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from typing import Annotated, Any, Literal

from ..models import (
    Alert,
    Clause,
    CoherenceCategory,
    EnrichedCoherenceResult,
    FindingSignal,
)

# =============================================================================
# CLAUSE WITH EMBEDDING
# =============================================================================


@dataclass
class ClauseWithEmbedding:
    """
    A clause enriched with its embedding vector for RAG similarity checks.

    Used in the prepare_context and rag_similarity_check nodes to detect
    cross-document relationships via cosine similarity.

    Attributes:
        clause: The original Clause object
        embedding: Dense vector representation (1536 dims for OpenAI ada-002)
        category: Inferred clause category (BUDGET, TIME, LEGAL, etc.)
        document_type: Source document type (contract, budget, schedule, bom)
    """

    clause: Clause
    embedding: list[float] = field(default_factory=list)
    category: CoherenceCategory = "SCOPE"
    document_type: Literal["contract", "budget", "schedule", "bom", "other"] = "other"

    @property
    def clause_id(self) -> str:
        """Convenience accessor for clause.id."""
        return self.clause.id

    @property
    def text(self) -> str:
        """Convenience accessor for clause.text."""
        return self.clause.text

    @property
    def data(self) -> dict[str, Any]:
        """Convenience accessor for clause.data."""
        return self.clause.data

    def has_embedding(self) -> bool:
        """Check if embedding has been computed."""
        return len(self.embedding) > 0


# =============================================================================
# CROSS-CLAUSE PAIR
# =============================================================================


@dataclass
class CrossClausePair:
    """
    A pair of clauses identified for cross-clause analysis.

    Generated by RAG similarity detection or category-based matching
    to check for contradictions, inconsistencies, or gaps.

    Attributes:
        clause_a: First clause in the pair
        clause_b: Second clause in the pair
        similarity_score: Cosine similarity (0.0-1.0) if from RAG
        match_reason: Why these clauses were paired
    """

    clause_a: ClauseWithEmbedding
    clause_b: ClauseWithEmbedding
    similarity_score: float = 0.0
    match_reason: str = "category_match"


# =============================================================================
# EVALUATION CONFIGURATION
# =============================================================================


@dataclass
class EvaluationConfig:
    """
    Configuration for the coherence evaluation run.

    Passed into the graph to control behavior like:
    - low_budget_mode: Skip LLM calls to reduce cost
    - parallel_evaluation: Run evaluators concurrently
    - include_cross_clause: Run cross-document analysis
    """

    low_budget_mode: bool = True
    parallel_evaluation: bool = True
    include_cross_clause: bool = True
    include_rag_similarity: bool = True
    poor_extraction_quality: bool = False
    missing_dimensions: list[str] | None = None
    llm_batch_size: int = 5
    similarity_threshold: float = 0.85
    max_cross_pairs: int = 20
    tenant_id: str | None = None
    project_id: str | None = None


# =============================================================================
# COVERAGE MAP REDUCER
# =============================================================================


def merge_coverage(
    left: dict[str, bool], right: dict[str, bool]
) -> dict[str, bool]:
    """LangGraph reducer: a category is assessed if assessed in EITHER branch."""
    merged = dict(left)
    for category, assessed in right.items():
        merged[category] = merged.get(category, False) or assessed
    return merged


# =============================================================================
# COHERENCE GRAPH STATE
# =============================================================================


@dataclass
class CoherenceGraphState:
    """
    The state object passed through all nodes in the coherence subgraph.

    LangGraph uses this to track state as it flows through:
        prepare_context → [det, rag, llm] (parallel) → cross_clause → scoring → format

    Attributes:
        # Input
        project_id: Unique project identifier
        clauses: Raw input clauses to evaluate
        config: Evaluation configuration

        # Enriched context (from prepare_context)
        enriched_clauses: Clauses with embeddings and categories
        cross_pairs: Clause pairs for cross-document analysis

        # Findings (from evaluators)
        deterministic_signals: Findings from deterministic rules (Agent A)
        llm_signals: Findings from LLM semantic analysis (Agent B)
        cross_signals: Findings from cross-clause analysis

        # Scoring (from scoring_arbiter)
        all_signals: Combined signals from all sources
        score: Final coherence score (5.0-97.0), or None when evidence is insufficient
        diagnostics: Detailed scoring breakdown

        # Output (from format_output)
        alerts: Legacy Alert objects for backward compat
        result: Final EnrichedCoherenceResult

        # Metadata
        errors: Any errors encountered during evaluation
        llm_cost_usd: Total LLM cost for this run
        llm_calls_count: Number of LLM API calls
    """

    # Input
    project_id: str = ""
    clauses: list[Clause] = field(default_factory=list)
    config: EvaluationConfig = field(default_factory=EvaluationConfig)

    # Enriched context
    enriched_clauses: list[ClauseWithEmbedding] = field(default_factory=list)
    cross_pairs: list[CrossClausePair] = field(default_factory=list)

    # Findings from evaluators (use Annotated for LangGraph reducers)
    deterministic_signals: Annotated[list[FindingSignal], operator.add] = field(
        default_factory=list
    )
    llm_signals: Annotated[list[FindingSignal], operator.add] = field(
        default_factory=list
    )
    cross_signals: Annotated[list[FindingSignal], operator.add] = field(
        default_factory=list
    )
    coverage_map: Annotated[dict[str, bool], merge_coverage] = field(
        default_factory=dict
    )

    # Scoring output
    all_signals: list[FindingSignal] = field(default_factory=list)
    score: float | None = None
    diagnostics: dict[str, Any] = field(default_factory=dict)

    # Final output
    alerts: list[Alert] = field(default_factory=list)
    result: EnrichedCoherenceResult | None = None

    # Metadata
    errors: Annotated[list[str], operator.add] = field(default_factory=list)
    llm_cost_usd: float = 0.0
    llm_calls_count: int = 0

    @property
    def num_clauses(self) -> int:
        """Number of clauses being evaluated."""
        return len(self.clauses)

    @property
    def total_findings(self) -> int:
        """Total number of findings from all sources."""
        return (
            len(self.deterministic_signals)
            + len(self.llm_signals)
            + len(self.cross_signals)
        )

    @property
    def tenant_id(self) -> str | None:
        """TS-OBS-COH-001: Canonical tenant accessor for graph integrations."""
        return self.config.tenant_id

    def has_errors(self) -> bool:
        """Check if any errors occurred during evaluation."""
        return len(self.errors) > 0


# =============================================================================
# TYPE ALIASES FOR LANGGRAPH
# =============================================================================

# LangGraph node function signature
# Each node receives state and returns partial state updates
NodeInput = CoherenceGraphState
NodeOutput = dict[str, Any]  # Partial state update


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "ClauseWithEmbedding",
    "CrossClausePair",
    "EvaluationConfig",
    "CoherenceGraphState",
    "NodeInput",
    "NodeOutput",
    "merge_coverage",
]
