import type { Project, Alert, Stakeholder, Activity, KPIData } from '@/types/project';

export const mockKPIData: KPIData = {
  coherenceScore: 78,
  coherenceTrend: 2,
  activeProjects: 12,
  projectsAtRisk: 3,
  openAlerts: 7,
  criticalAlerts: 3,
  budgetUsed: 62,
};

export const mockProjects: Project[] = [
  {
    id: 'PROJ-001',
    name: 'Petrochemical Plant EPC',
    description: 'Full EPC delivery for greenfield petrochemical facility',
    status: 'active',
    coherence_score: 78,
    open_alerts: 7,
    critical_alerts: 3,
    budget_used: 62,
    updated_at: '2026-01-14T10:30:00Z',
    created_at: '2025-06-15T08:00:00Z',
  },
  {
    id: 'PROJ-002',
    name: 'Refinery Modernization',
    description: 'Equipment upgrades and process optimization',
    status: 'active',
    coherence_score: 64,
    open_alerts: 12,
    critical_alerts: 5,
    budget_used: 45,
    updated_at: '2026-01-15T14:20:00Z',
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'PROJ-003',
    name: 'Gas Pipeline Extension',
    description: '120km pipeline with 3 compression stations',
    status: 'on_hold',
    coherence_score: 92,
    open_alerts: 2,
    critical_alerts: 0,
    budget_used: 28,
    updated_at: '2026-01-10T09:15:00Z',
    created_at: '2025-11-20T08:00:00Z',
  },
  {
    id: 'PROJ-004',
    name: 'Solar Farm Installation',
    description: '500MW utility-scale solar installation',
    status: 'active',
    coherence_score: 85,
    open_alerts: 4,
    critical_alerts: 1,
    budget_used: 71,
    updated_at: '2026-01-16T08:45:00Z',
    created_at: '2025-03-10T08:00:00Z',
  },
  {
    id: 'PROJ-005',
    name: 'LNG Terminal Phase 2',
    description: 'Capacity expansion of existing LNG terminal',
    status: 'completed',
    coherence_score: 94,
    open_alerts: 1,
    critical_alerts: 0,
    budget_used: 98,
    updated_at: '2026-01-08T16:00:00Z',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'PROJ-006',
    name: 'Water Treatment Facility',
    description: 'Industrial water treatment and recycling plant',
    status: 'active',
    coherence_score: 71,
    open_alerts: 8,
    critical_alerts: 2,
    budget_used: 54,
    updated_at: '2026-01-15T11:30:00Z',
    created_at: '2025-07-01T08:00:00Z',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'AL-001',
    project_id: 'PROJ-001',
    project_name: 'Petrochemical Plant EPC',
    severity: 'critical',
    type: 'Legal',
    title: 'Contract Penalty Clause Violation Risk',
    description: 'Clause 4.2.1 specifies 30-day delay penalty. Current trajectory shows 45-day delay.',
    status: 'open',
    created_at: '2026-01-15T14:30:00Z',
    updated_at: '2026-01-15T14:30:00Z',
  },
  {
    id: 'AL-002',
    project_id: 'PROJ-001',
    project_name: 'Petrochemical Plant EPC',
    severity: 'critical',
    type: 'Financial',
    title: 'Budget Overrun Threshold Exceeded',
    description: 'Equipment procurement costs 23% above baseline estimates.',
    status: 'open',
    created_at: '2026-01-14T09:15:00Z',
    updated_at: '2026-01-14T09:15:00Z',
  },
  {
    id: 'AL-003',
    project_id: 'PROJ-002',
    project_name: 'Refinery Modernization',
    severity: 'critical',
    type: 'Technical',
    title: 'Equipment Compatibility Issue',
    description: 'New compressor specifications conflict with existing infrastructure.',
    status: 'in_progress',
    created_at: '2026-01-13T16:45:00Z',
    updated_at: '2026-01-15T10:20:00Z',
  },
  {
    id: 'AL-004',
    project_id: 'PROJ-001',
    project_name: 'Petrochemical Plant EPC',
    severity: 'high',
    type: 'Schedule',
    title: 'Critical Path Delay - Foundation Work',
    description: 'Foundation completion delayed by 12 days due to ground conditions.',
    status: 'open',
    created_at: '2026-01-12T11:00:00Z',
    updated_at: '2026-01-12T11:00:00Z',
  },
  {
    id: 'AL-005',
    project_id: 'PROJ-004',
    project_name: 'Solar Farm Installation',
    severity: 'high',
    type: 'Scope',
    title: 'Grid Connection Requirements Changed',
    description: 'Utility company issued new interconnection requirements.',
    status: 'open',
    created_at: '2026-01-11T08:30:00Z',
    updated_at: '2026-01-11T08:30:00Z',
  },
  {
    id: 'AL-006',
    project_id: 'PROJ-002',
    project_name: 'Refinery Modernization',
    severity: 'medium',
    type: 'Financial',
    title: 'Material Cost Variance',
    description: 'Steel prices increased 8% above budgeted rates.',
    status: 'open',
    created_at: '2026-01-10T13:20:00Z',
    updated_at: '2026-01-10T13:20:00Z',
  },
  {
    id: 'AL-007',
    project_id: 'PROJ-006',
    project_name: 'Water Treatment Facility',
    severity: 'medium',
    type: 'Legal',
    title: 'Permit Renewal Pending',
    description: 'Environmental permit expires in 45 days. Renewal application in progress.',
    status: 'in_progress',
    created_at: '2026-01-09T15:00:00Z',
    updated_at: '2026-01-14T09:00:00Z',
  },
  {
    id: 'AL-008',
    project_id: 'PROJ-003',
    project_name: 'Gas Pipeline Extension',
    severity: 'low',
    type: 'Schedule',
    title: 'Weather Delay - Minor',
    description: 'Expected 3-day delay due to adverse weather conditions.',
    status: 'resolved',
    created_at: '2026-01-08T10:00:00Z',
    updated_at: '2026-01-10T14:30:00Z',
  },
];

export const mockStakeholders: Stakeholder[] = [
  {
    id: 'STK-001',
    name: 'John Mitchell',
    email: 'j.mitchell@client.com',
    role: 'Project Sponsor',
    organization: 'Client Corp',
    power: 9,
    interest: 9,
    engagement: 'critical',
    initials: 'JM',
  },
  {
    id: 'STK-002',
    name: 'Sarah Chen',
    email: 's.chen@epc.com',
    role: 'Project Manager',
    organization: 'EPC Contractor',
    power: 8,
    interest: 10,
    engagement: 'critical',
    initials: 'SC',
  },
  {
    id: 'STK-003',
    name: 'Robert Williams',
    email: 'r.williams@client.com',
    role: 'CFO',
    organization: 'Client Corp',
    power: 9,
    interest: 4,
    engagement: 'important',
    initials: 'RW',
  },
  {
    id: 'STK-004',
    name: 'Maria Garcia',
    email: 'm.garcia@legal.com',
    role: 'Legal Counsel',
    organization: 'Legal Partners LLP',
    power: 7,
    interest: 3,
    engagement: 'monitoring',
    initials: 'MG',
  },
  {
    id: 'STK-005',
    name: 'David Kim',
    email: 'd.kim@epc.com',
    role: 'Lead Engineer',
    organization: 'EPC Contractor',
    power: 4,
    interest: 9,
    engagement: 'important',
    initials: 'DK',
  },
  {
    id: 'STK-006',
    name: 'Lisa Brown',
    email: 'l.brown@qa.com',
    role: 'QA Manager',
    organization: 'EPC Contractor',
    power: 3,
    interest: 8,
    engagement: 'monitoring',
    initials: 'LB',
  },
  {
    id: 'STK-007',
    name: 'James Taylor',
    email: 'j.taylor@vendor.com',
    role: 'Equipment Supplier',
    organization: 'Tech Vendors Inc',
    power: 3,
    interest: 4,
    engagement: 'monitoring',
    initials: 'JT',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'ACT-001',
    type: 'alert_created',
    description: 'Critical alert raised: Contract Penalty Clause Violation Risk',
    timestamp: '2026-01-15T14:30:00Z',
    metadata: { alertId: 'AL-001', severity: 'critical' },
  },
  {
    id: 'ACT-002',
    type: 'document_uploaded',
    description: 'Contract amendment v3 uploaded for review',
    timestamp: '2026-01-15T11:20:00Z',
    metadata: { documentType: 'Contract' },
  },
  {
    id: 'ACT-003',
    type: 'score_changed',
    description: 'Coherence score increased from 76 to 78',
    timestamp: '2026-01-14T16:00:00Z',
    metadata: { oldScore: 76, newScore: 78 },
  },
  {
    id: 'ACT-004',
    type: 'alert_resolved',
    description: 'Alert resolved: Weather Delay - Minor',
    timestamp: '2026-01-10T14:30:00Z',
    metadata: { alertId: 'AL-008' },
  },
  {
    id: 'ACT-005',
    type: 'stakeholder_added',
    description: 'New stakeholder added: Lisa Brown (QA Manager)',
    timestamp: '2026-01-09T09:00:00Z',
    metadata: { stakeholderId: 'STK-006' },
  },
];
