/**
 * Test Suite ID: TS-P0D-REPORT-UI-001
 * Representative Current State Report payload for UI tests.
 */
import type { CurrentStateReport } from "@/lib/api/generated/models";

const PROJECT_ID = "5d5c2a3e-1f7e-4c4a-9a51-2d9a7b0c1e11";

export function buildCurrentStateReport(): CurrentStateReport {
  return {
    report_schema_version: "current-state-report/v2",
    generated_at: "2026-09-13T12:00:00Z",
    project: { id: PROJECT_ID, name: "Hospital North", code: "HN-01", status: "active" },
    content_fingerprint: "a3f1c9d2e4b5a6978877665544332211ffeeddccbbaa99887766554433221100",
    sections: {
      executive_summary: {
        status: "available",
        status_reason: null,
        source_domain: "report",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: "Derived from the sections of this report; see each section for its evidence quality.",
        data: {
          attention_items: [
            {
              kind: "alerts_high_severity",
              level: "critical",
              message: "2 open critical or high-severity alert(s).",
              section_key: "alerts",
            },
            {
              kind: "section_error",
              level: "warning",
              message: "Some report sections could not be read: wbs.",
              section_key: "wbs",
            },
            {
              kind: "hitl_pending",
              level: "info",
              message: "4 review item(s) await a human decision.",
              section_key: "hitl",
            },
          ],
          document_count: 45,
          parsed_document_count: null,
          analyzed_document_count: null,
          awaiting_analysis_document_count: null,
          error_section_keys: ["wbs"],
          unavailable_section_keys: [],
          not_modeled_section_keys: ["risks", "obligations", "schedule"],
        },
      },
      documents: {
        status: "available",
        status_reason: null,
        source_domain: "documents",
        source_as_of: "2026-09-12T08:00:00Z",
        evidence_tier: "strong_linked",
        evidence_note: "Each entry is a source document record.",
        data: {
          total: 45,
          by_processing_status: { parsed: 20 },
          by_lifecycle_status: { analyzed: 20 },
          by_type: { contract: 20 },
          counts_are_partial: true,
          items: [
            {
              id: "d0c1a8f6-8e2a-4f7b-a8a9-5a6b7c8d9e01",
              filename: "Main Contract.pdf",
              document_type: "contract",
              upload_status: "analyzed",
              processing_status: "parsed",
              lifecycle_status: "analyzed",
              version: 2,
              uploaded_at: "2026-09-10T10:00:00Z",
              parsed_at: "2026-09-10T10:05:00Z",
            },
          ],
          truncated: true,
        },
      },
      health: {
        status: "available",
        status_reason: null,
        source_domain: "health",
        source_as_of: "2026-09-12T09:00:00Z",
        source_ref: "project_snapshot:7e1d2c3b-4a5f-4e6d-8c7b-9a0f1e2d3c4b",
        evidence_tier: "weak_linked",
        evidence_note: "4 category evidence reference(s) identify persisted contract clauses (clause-level granularity).",
        data: {
          computed_at: "2026-09-12T09:00:00Z",
          evidence_granularity: "clause",
          categories: [
            { category: "SCOPE", state: "present", evidence_count: 1, missing_data: [], gap: null },
            {
              category: "BUDGET",
              state: "insufficient_evidence",
              evidence_count: 0,
              missing_data: ["budget / bill of quantities (BoQ) not detected"],
              gap: "Upload the budget or bill of quantities (BoQ) to assess BUDGET.",
            },
            {
              category: "TIME",
              state: "insufficient_evidence",
              evidence_count: 0,
              missing_data: ["project schedule / cronograma not detected"],
              gap: "Upload the project schedule (cronograma) to assess TIME.",
            },
            { category: "TECHNICAL", state: "present", evidence_count: 2, missing_data: [], gap: null },
            { category: "LEGAL", state: "present", evidence_count: 1, missing_data: [], gap: null },
            {
              category: "QUALITY",
              state: "insufficient_evidence",
              evidence_count: 0,
              missing_data: ["quality plan / acceptance criteria not detected"],
              gap: "Upload the quality plan / acceptance criteria to assess QUALITY.",
            },
          ],
        },
      },
      missing_evidence: {
        status: "available",
        status_reason: null,
        source_domain: "report",
        source_as_of: "2026-09-12T09:00:00Z",
        evidence_tier: "unlinked",
        evidence_note: "Gap statements describe what is absent; they are not tied to source locations.",
        data: {
          items: [
            {
              source_domain: "health",
              subject: "BUDGET",
              description: "budget / bill of quantities (BoQ) not detected",
            },
            {
              source_domain: "coherence",
              subject: "budget",
              description: "No evidence for this coherence dimension.",
            },
          ],
        },
      },
      coherence: {
        status: "available",
        status_reason: null,
        source_domain: "coherence",
        source_as_of: null,
        evidence_tier: "unlinked",
        evidence_note: "Coherence scores are aggregates; per-finding evidence is reported under Alerts.",
        data: {
          score: null,
          score_version: "coherence-v2",
          score_reason: "insufficient_evidence",
          missing_dimensions: ["budget"],
          sub_scores: { SCOPE: 80, BUDGET: null },
          evaluation_alert_count: 3,
          last_activity_at: "2026-09-12T07:00:00Z",
        },
      },
      alerts: {
        status: "available",
        status_reason: null,
        source_domain: "alerts",
        source_as_of: "2026-09-12T11:00:00Z",
        evidence_tier: "unlinked",
        evidence_note:
          "Across all 3 alert(s), including resolved and dismissed: some alerts record no source clause or affected entity.",
        data: {
          total: 3,
          open_count: 2,
          open_by_severity: { critical: 1, high: 1 },
          overdue_open_count: 1,
          items: [
            {
              id: "a1a1a1a1-0000-4000-8000-000000000001",
              title: "Penalty clause conflicts with schedule",
              severity: "critical",
              category: "LEGAL",
              status: "open",
              created_at: "2026-09-13T07:00:00Z",
              sla_due_at: "2026-09-13T09:00:00Z",
              overdue: true,
              source_clause_id: "c1c1c1c1-0000-4000-8000-000000000001",
              evidence_tier: "strong_linked",
            },
            {
              id: "a1a1a1a1-0000-4000-8000-000000000002",
              title: "Budget total differs from contract price",
              severity: "high",
              category: "BUDGET",
              status: "open",
              created_at: "2026-09-13T11:00:00Z",
              sla_due_at: "2026-09-14T11:00:00Z",
              overdue: false,
              source_clause_id: null,
              evidence_tier: "unlinked",
            },
          ],
          truncated: false,
          evidence_breakdown: { strong_linked: 1, weak_linked: 0, unlinked: 2 },
        },
      },
      hitl: {
        status: "available",
        status_reason: null,
        source_domain: "hitl",
        source_as_of: "2026-09-12T10:00:00Z",
        evidence_tier: "unlinked",
        evidence_note: "Review items carry no structured source reference. Pending counts include escalated items.",
        data: {
          pending_count: 4,
          overdue_count: null,
          items: [
            {
              item_id: "b2b2b2b2-0000-4000-8000-000000000001",
              item_type: "analysis_critique",
              status: "PENDING_REVIEW_REQUIRED",
              impact_level: "HIGH",
              confidence: 0.4,
              created_at: "2026-09-12T10:00:00Z",
              sla_due_date: "2026-09-14T10:00:00Z",
              overdue: false,
            },
          ],
          truncated: true,
        },
      },
      budget: {
        status: "available",
        status_reason: null,
        source_domain: "procurement.budget",
        source_as_of: null,
        evidence_tier: "unlinked",
        evidence_note: "Budget items record no source document or clause reference, and no timestamps.",
        data: {
          item_count: 1,
          total_budget: "1250.50",
          spent_amount: "0",
          spend_recorded: false,
          remaining_budget: null,
          currency: "EUR",
          notes: [
            "Currency is the system default; it is not extracted from contract evidence.",
            "Remaining budget is not shown because no spend has been recorded.",
          ],
          items: [
            { id: "e3e3e3e3-0000-4000-8000-000000000001", name: "Civil works", code: "B-01", amount: "1250.50" },
          ],
          truncated: false,
        },
      },
      wbs: {
        status: "error",
        status_reason: "This source could not be read when the report was generated.",
        source_domain: "wbs",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: null,
        data: null,
      },
      stakeholders: {
        status: "available",
        status_reason: null,
        source_domain: "stakeholders",
        source_as_of: "2026-09-11T10:00:00Z",
        evidence_tier: "weak_linked",
        evidence_note: "Some stakeholders reference only their source document.",
        data: {
          total: 800,
          key_player_count: null,
          by_quadrant: { key_player: 1 },
          counts_are_partial: true,
          items: [
            {
              id: "f4f4f4f4-0000-4000-8000-000000000001",
              name: "Ana García",
              role: "Project Director",
              organization: "Owner",
              quadrant: "key_player",
              evidence_tier: "weak_linked",
            },
          ],
          truncated: true,
          evidence_breakdown: { strong_linked: 0, weak_linked: 1, unlinked: 0 },
        },
      },
      raci: {
        status: "available",
        status_reason: null,
        source_domain: "stakeholders.raci",
        source_as_of: null,
        evidence_tier: "unlinked",
        evidence_note: "RACI assignments show verification status but carry no source reference in this report.",
        data: {
          task_count: 2,
          assignment_count: 3,
          verified_assignment_count: 1,
          tasks_without_accountable: 1,
          tasks: [
            {
              task_code: "1.1",
              task_name: "Foundations",
              accountable: ["Ana García"],
              responsible: ["Luis"],
              assignment_count: 2,
              verified_count: 1,
            },
            {
              task_code: "1.2",
              task_name: "Structure",
              accountable: [],
              responsible: ["Luis"],
              assignment_count: 1,
              verified_count: 0,
            },
          ],
          truncated: false,
        },
      },
      risks: {
        status: "not_modeled",
        status_reason:
          "C2Pro does not yet maintain a project risk register. Risk-type findings are reported under Alerts.",
        source_domain: "none",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: null,
        data: null,
      },
      obligations: {
        status: "not_modeled",
        status_reason: "Contract obligations are not yet tracked as a project-level register.",
        source_domain: "none",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: null,
        data: null,
      },
      schedule: {
        status: "not_modeled",
        status_reason:
          "Schedule and milestone tracking is not modeled yet; the Health schedule dimension is deferred until schedule baselines can be ingested.",
        source_domain: "none",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: null,
        data: null,
      },
      evidence_quality: {
        status: "available",
        status_reason: null,
        source_domain: "report",
        source_as_of: null,
        evidence_tier: "unavailable",
        evidence_note: "Summarizes the evidence quality of every section in this report.",
        data: {
          rows: [
            { section_key: "documents", status: "available", evidence_tier: "strong_linked", evidence_note: "Each entry is a source document record." },
            { section_key: "health", status: "available", evidence_tier: "unlinked", evidence_note: "No dimension cites supporting evidence." },
            { section_key: "missing_evidence", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "coherence", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "alerts", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "hitl", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "budget", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "wbs", status: "error", evidence_tier: "unavailable", evidence_note: "This source could not be read when the report was generated." },
            { section_key: "stakeholders", status: "available", evidence_tier: "weak_linked", evidence_note: null },
            { section_key: "raci", status: "available", evidence_tier: "unlinked", evidence_note: null },
            { section_key: "risks", status: "not_modeled", evidence_tier: "unavailable", evidence_note: null },
            { section_key: "obligations", status: "not_modeled", evidence_tier: "unavailable", evidence_note: null },
            { section_key: "schedule", status: "not_modeled", evidence_tier: "unavailable", evidence_note: null },
          ],
          available_section_tiers: { strong_linked: 1, weak_linked: 1, unlinked: 7 },
        },
      },
    },
  };
}
