from typing import Any, Literal
from datetime import datetime

from pydantic import BaseModel, Field

# Define valid alert categories as a type
AlertCategory = Literal["legal", "financial", "technical", "schedule", "scope", "quality"]


class Clause(BaseModel):
    """
    Represents a specific clause or segment of a document.
    """

    id: str = Field(..., description="Unique identifier for the clause.")
    text: str = Field(..., description="The textual content of the clause.")
    data: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured data extracted from or associated with the clause (e.g., budget figures, dates, status).",
    )


class ProjectContext(BaseModel):
    """
    Represents the full context of a project to be evaluated, now with structured clauses.
    """

    id: str = Field(..., description="Unique identifier for the project.")
    clauses: list[Clause] = Field(
        default_factory=list,
        description="List of structured clauses from documents relevant to the project.",
    )


class Evidence(BaseModel):
    """
    Represents the specific evidence supporting an alert.
    """

    source_clause_id: str = Field(
        ..., description="The ID of the clause that serves as direct evidence."
    )
    claim: str = Field(..., description="A concise claim or summary derived from the evidence.")
    quote: str = Field(
        ..., description="The direct quote from the clause text that serves as evidence."
    )
    # Additional fields can be added here in future iterations, e.g., confidence, page_number.


class Alert(BaseModel):
    """
    Represents an alert generated by a rule.
    """

    rule_id: str = Field(..., description="The ID of the rule that triggered this alert.")
    severity: str = Field(
        ..., description="The severity of the triggered alert (e.g., critical, high, medium, low)."
    )
    category: AlertCategory = Field(
        ..., description="The category of the alert (legal, financial, technical, schedule, scope)."
    )
    message: str = Field(..., description="A descriptive message for the alert.")
    evidence: Evidence = Field(..., description="Structured evidence supporting the alert.")


class SeverityCount(BaseModel):
    """
    Represents the count of alerts by severity level.
    """

    critical: int = Field(default=0, description="Number of critical alerts.")
    high: int = Field(default=0, description="Number of high severity alerts.")
    medium: int = Field(default=0, description="Number of medium severity alerts.")
    low: int = Field(default=0, description="Number of low severity alerts.")


class CategoryBreakdown(BaseModel):
    """
    Represents the coherence score breakdown for a specific category.
    """

    category: AlertCategory = Field(..., description="The alert category.")
    score: float = Field(..., description="The coherence score for this category (0-100).")
    alert_count: int = Field(..., description="Total number of alerts in this category.")
    severity_breakdown: SeverityCount = Field(
        ..., description="Breakdown of alerts by severity within this category."
    )
    impact_percentage: float = Field(
        ..., description="Percentage of impact this category has on the overall score."
    )


class CoherenceResult(BaseModel):
    """
    Represents the complete result of a coherence evaluation, including alerts and the final score.
    """

    overall_score: float = Field(..., description="The overall calculated coherence score for the project.")
    alerts: list[Alert] = Field(..., description="List of alerts generated during the evaluation.")
    category_breakdown: list[CategoryBreakdown] = Field(
        default_factory=list,
        description="Breakdown of the score by alert category."
    )
    calculated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the score was calculated."
    )
