from typing import Any

from pydantic import BaseModel, Field


class Clause(BaseModel):
    """
    Represents a specific clause or segment of a document.
    """

    id: str = Field(..., description="Unique identifier for the clause.")
    text: str = Field(..., description="The textual content of the clause.")
    data: dict[str, Any] = Field(
        default_factory=dict,
        description="Structured data extracted from or associated with the clause (e.g., budget figures, dates, status).",
    )


class ProjectContext(BaseModel):
    """
    Represents the full context of a project to be evaluated, now with structured clauses.
    """

    id: str = Field(..., description="Unique identifier for the project.")
    clauses: list[Clause] = Field(
        default_factory=list,
        description="List of structured clauses from documents relevant to the project.",
    )


class Evidence(BaseModel):
    """
    Represents the specific evidence supporting an alert.
    """

    source_clause_id: str = Field(
        ..., description="The ID of the clause that serves as direct evidence."
    )
    claim: str = Field(..., description="A concise claim or summary derived from the evidence.")
    quote: str = Field(
        ..., description="The direct quote from the clause text that serves as evidence."
    )
    # Additional fields can be added here in future iterations, e.g., confidence, page_number.


class Alert(BaseModel):
    """
    Represents an alert generated by a rule.
    """

    rule_id: str = Field(..., description="The ID of the rule that triggered this alert.")
    severity: str = Field(
        ..., description="The severity of the triggered alert (e.g., critical, high, medium, low)."
    )
    message: str = Field(..., description="A descriptive message for the alert.")
    evidence: Evidence = Field(..., description="Structured evidence supporting the alert.")


class CoherenceResult(BaseModel):
    """
    Represents the complete result of a coherence evaluation, including alerts and the final score.
    """

    alerts: list[Alert] = Field(..., description="List of alerts generated during the evaluation.")
    score: float = Field(..., description="The calculated coherence score for the project.")
