"""
QA Swarm — LangGraph Orchestrator

Builds and executes the multi-agent QA pipeline:

    ContextAnalyzerAgent
          │
    TestGenerationAgent
          │
    QAReviewerAgent ──(issues + iterations < 2)──► TestGenerationAgent (retry)
          │
    commit_or_output ──► END
          │
    [on error] ──────────────────────────────────► END

Usage (CLI):

    # Dry run — print generated test to stdout
    python -m scripts.agents.qa_swarm.qa_swarm_orchestrator \\
      --target-file apps/api/src/coherence/engine_v2.py \\
      --coverage-xml apps/api/coverage.xml \\
      --dry-run

    # Write generated test to a local file
    python -m scripts.agents.qa_swarm.qa_swarm_orchestrator \\
      --target-file apps/api/src/analysis/adapters/graph/workflow.py \\
      --coverage-xml apps/api/coverage.xml \\
      --output-path /tmp/test_workflow_swarm.py

    # PR mode — process all Python files changed in a PR
    python -m scripts.agents.qa_swarm.qa_swarm_orchestrator \\
      --repo AI-Gen-AI/C2Pro \\
      --pr-number 42 \\
      --coverage-xml ci-artifacts/coverage.xml

Environment variables:
    ANTHROPIC_API_KEY   — required for all Claude API calls
    GITHUB_TOKEN        — required for PR mode (reading diffs, creating PRs)
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path
from typing import Any

from langgraph.graph import END, StateGraph

# ---------------------------------------------------------------------------
# Agent imports
# ---------------------------------------------------------------------------

from .context_analyzer_agent import analyze_context
from .qa_reviewer_agent import review_tests, should_regenerate
from .state import QASwarmState, make_initial_state
from .test_generator_agent import generate_tests

# ---------------------------------------------------------------------------
# commit_or_output node
# ---------------------------------------------------------------------------


async def commit_or_output(state: QASwarmState) -> QASwarmState:
    """
    Final node: write the approved test file to disk or commit it to GitHub.

    In standalone mode (no GITHUB_TOKEN / repo info), writes the file locally.
    In PR mode, uses scripts/agents/base.py utilities to create a branch and
    open a draft PR.
    """
    final_code = state.get("final_test_code", "")
    test_file_path = state.get("test_file_path", "")

    if not final_code:
        return {
            **state,
            "committed": False,
        }

    output_path: str | None = state.get("_output_path")  # type: ignore[assignment]
    dry_run: bool = state.get("_dry_run", False)  # type: ignore[assignment]

    if dry_run:
        print("=" * 80)
        print(f"[DRY RUN] Generated test file: {test_file_path}")
        print("=" * 80)
        print(final_code)
        print("=" * 80)
        return {**state, "committed": False}

    # Determine write path
    write_path = output_path or test_file_path
    if not write_path:
        return {**state, "committed": False}

    Path(write_path).parent.mkdir(parents=True, exist_ok=True)
    Path(write_path).write_text(final_code, encoding="utf-8")
    print(f"[QA Swarm] Test file written: {write_path}")

    # Optionally commit to GitHub via base.py utilities
    github_token = os.environ.get("GITHUB_TOKEN")
    repo_name: str | None = state.get("_repo_name")  # type: ignore[assignment]
    base_sha: str | None = state.get("_base_sha")  # type: ignore[assignment]

    if github_token and repo_name and base_sha and write_path:
        try:
            from scripts.agents.base import (
                create_branch_and_commit,
                get_github_client,
                get_repo,
                open_draft_pr,
            )

            gh = get_github_client()
            repo = get_repo(gh, repo_name)
            branch_name = f"qa-swarm/auto-tests-{Path(write_path).stem}"

            create_branch_and_commit(
                repo=repo,
                base_sha=base_sha,
                branch_name=branch_name,
                file_path=write_path,
                new_content=final_code,
                commit_message=(
                    f"test(qa-swarm): auto-generate tests for "
                    f"{state.get('target_file', 'unknown')}"
                ),
            )

            target = state.get("target_file", "unknown")
            pr = open_draft_pr(
                repo=repo,
                head_branch=branch_name,
                base_branch="develop",
                title=f"[QA Swarm] Auto-generated tests for `{Path(target).name}`",
                body=(
                    f"## Auto-generated by QA Swarm\n\n"
                    f"**Target file:** `{target}`\n\n"
                    f"**Generated by:** ContextAnalyzerAgent → TestGenerationAgent → QAReviewerAgent\n\n"
                    f"**Scenarios covered:** {len(state.get('test_scenarios', []))}\n\n"
                    f"**Review iterations:** {state.get('review_iterations', 0)}\n\n"
                    f"> ⚠️ This is an auto-generated draft. A human must review before merging.\n"
                ),
            )
            print(f"[QA Swarm] Draft PR created: {pr.html_url}")
        except Exception as exc:
            print(f"[QA Swarm] GitHub commit failed (local file still written): {exc}")

    return {**state, "committed": True}


# ---------------------------------------------------------------------------
# Graph builder
# ---------------------------------------------------------------------------


def build_qa_swarm() -> Any:
    """
    Construct the compiled LangGraph StateGraph for the QA swarm.

    Graph topology:
        context_analyzer → test_generator → qa_reviewer
          └─ (regenerate) ─────────────────►┘
          └─ (approve)    → commit_or_output → END
          └─ (fail)       → END

    The ``error`` field in state acts as a global abort — any node can set it
    and the orchestrator will route to END after the current node completes.
    """
    workflow = StateGraph(QASwarmState)

    workflow.add_node("context_analyzer", analyze_context)
    workflow.add_node("test_generator", generate_tests)
    workflow.add_node("qa_reviewer", review_tests)
    workflow.add_node("commit_or_output", commit_or_output)

    # ── Entry point ──
    workflow.set_entry_point("context_analyzer")

    # ── Error guard: abort on fatal error ──
    def _check_error(state: QASwarmState) -> str:
        if state.get("error"):
            return "end"
        return "continue"

    workflow.add_conditional_edges(
        "context_analyzer",
        _check_error,
        {"end": END, "continue": "test_generator"},
    )

    workflow.add_conditional_edges(
        "test_generator",
        _check_error,
        {"end": END, "continue": "qa_reviewer"},
    )

    # ── Review outcome routing ──
    workflow.add_conditional_edges(
        "qa_reviewer",
        should_regenerate,
        {
            "regenerate": "test_generator",
            "approve": "commit_or_output",
            "fail": END,
        },
    )

    workflow.add_edge("commit_or_output", END)

    return workflow.compile()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def run_qa_swarm(
    target_file: str,
    coverage_xml_path: str,
    pr_diff: str = "",
    output_path: str | None = None,
    dry_run: bool = False,
    repo_name: str | None = None,
    base_sha: str | None = None,
) -> dict[str, Any]:
    """
    Run the QA swarm for a single target source file.

    Args:
        target_file:        Repo-relative path to the source file to test.
        coverage_xml_path:  Path to the pytest-cov XML report.
        pr_diff:            Unified diff string (optional).
        output_path:        Where to write the generated test file locally.
        dry_run:            If True, print to stdout instead of writing.
        repo_name:          GitHub repo (e.g. "AI-Gen-AI/C2Pro") for PR mode.
        base_sha:           Base commit SHA for creating branches in PR mode.

    Returns:
        The final QASwarmState dictionary.
    """
    # Read source file
    if not os.path.exists(target_file):
        return {"error": f"Target file not found: {target_file}"}

    source_code = Path(target_file).read_text(encoding="utf-8")

    # Discover existing test files for this module
    module_stem = Path(target_file).stem
    existing_test_files: list[str] = []
    test_dirs = ["apps/api/tests"]
    for test_dir in test_dirs:
        if os.path.isdir(test_dir):
            for p in Path(test_dir).rglob(f"*{module_stem}*.py"):
                existing_test_files.append(str(p))

    initial_state = make_initial_state(
        target_file=target_file,
        source_code=source_code,
        coverage_report_path=coverage_xml_path,
        pr_diff=pr_diff,
        existing_test_files=existing_test_files,
    )
    # Inject orchestrator-level control fields
    initial_state["_output_path"] = output_path  # type: ignore[typeddict-unknown-key]
    initial_state["_dry_run"] = dry_run  # type: ignore[typeddict-unknown-key]
    initial_state["_repo_name"] = repo_name  # type: ignore[typeddict-unknown-key]
    initial_state["_base_sha"] = base_sha  # type: ignore[typeddict-unknown-key]

    app = build_qa_swarm()
    final_state = await app.ainvoke(initial_state)
    return final_state


async def run_qa_swarm_for_pr(
    repo_name: str,
    pr_number: int,
    base_sha: str,
    head_sha: str,
    coverage_xml_path: str,
    dry_run: bool = False,
) -> list[dict[str, Any]]:
    """
    Run the QA swarm for all Python source files touched in a PR that lack tests.

    Reads the PR diff from GitHub API, filters to ``apps/api/src/`` Python files
    that are not test files themselves, then runs ``run_qa_swarm`` for each.

    Args:
        repo_name:          GitHub repo (e.g. "AI-Gen-AI/C2Pro").
        pr_number:          Pull request number.
        base_sha:           Base commit SHA.
        head_sha:           Head commit SHA.
        coverage_xml_path:  Path to the pytest-cov XML report.
        dry_run:            If True, print to stdout instead of writing.

    Returns:
        List of final state dicts, one per processed file.
    """
    try:
        from scripts.agents.base import get_github_client, get_pr, get_pr_diff, get_repo
    except ImportError as exc:
        return [{"error": f"Could not import scripts.agents.base: {exc}"}]

    gh = get_github_client()
    repo = get_repo(gh, repo_name)
    diff = get_pr_diff(repo, base_sha, head_sha)

    # Extract Python source files from diff header lines
    changed_files: list[str] = []
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            path = line[6:].strip()
            if (
                path.endswith(".py")
                and "apps/api/src/" in path
                and "/test" not in path
                and "conftest" not in path
            ):
                changed_files.append(path)

    if not changed_files:
        print("[QA Swarm] No Python source files found in PR diff.")
        return []

    print(f"[QA Swarm] Processing {len(changed_files)} file(s) from PR #{pr_number}")

    results = []
    for file_path in changed_files:
        if not os.path.exists(file_path):
            print(f"[QA Swarm] Skipping (not found locally): {file_path}")
            continue
        print(f"[QA Swarm] → {file_path}")
        result = await run_qa_swarm(
            target_file=file_path,
            coverage_xml_path=coverage_xml_path,
            pr_diff=diff,
            dry_run=dry_run,
            repo_name=repo_name,
            base_sha=head_sha,
        )
        results.append(result)

    return results


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="qa_swarm_orchestrator",
        description="C2Pro QA Swarm — autonomous test generation pipeline",
    )
    parser.add_argument(
        "--target-file",
        help="Repo-relative path to the source file to analyse",
    )
    parser.add_argument(
        "--coverage-xml",
        required=True,
        help="Path to pytest-cov XML report (coverage.xml)",
    )
    parser.add_argument(
        "--output-path",
        help="Local path to write the generated test file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated test to stdout instead of writing",
    )
    parser.add_argument(
        "--repo",
        help="GitHub repo (e.g. AI-Gen-AI/C2Pro) for PR mode",
    )
    parser.add_argument(
        "--pr-number",
        type=int,
        help="Pull request number for PR mode",
    )
    parser.add_argument(
        "--base-sha",
        help="Base commit SHA (required for PR mode)",
    )
    parser.add_argument(
        "--head-sha",
        help="Head commit SHA (required for PR mode)",
    )
    return parser


async def _async_main(args: argparse.Namespace) -> int:
    if args.pr_number and args.repo:
        # PR mode
        if not args.base_sha or not args.head_sha:
            print("ERROR: --base-sha and --head-sha are required for PR mode", file=sys.stderr)
            return 1
        results = await run_qa_swarm_for_pr(
            repo_name=args.repo,
            pr_number=args.pr_number,
            base_sha=args.base_sha,
            head_sha=args.head_sha,
            coverage_xml_path=args.coverage_xml,
            dry_run=args.dry_run,
        )
        failed = [r for r in results if r.get("error")]
        if failed:
            for r in failed:
                print(f"ERROR: {r['error']}", file=sys.stderr)
            return 1
        return 0

    elif args.target_file:
        # Single file mode
        result = await run_qa_swarm(
            target_file=args.target_file,
            coverage_xml_path=args.coverage_xml,
            output_path=args.output_path,
            dry_run=args.dry_run,
            repo_name=args.repo,
            base_sha=args.base_sha,
        )
        if result.get("error"):
            print(f"ERROR: {result['error']}", file=sys.stderr)
            return 1
        if not result.get("review_passed") and not args.dry_run:
            issues = result.get("review_issues", [])
            print(f"WARNING: QA review did not pass. Issues: {issues}", file=sys.stderr)
            return 2
        return 0

    else:
        print("ERROR: provide --target-file or --pr-number + --repo", file=sys.stderr)
        return 1


def main() -> None:
    parser = _build_arg_parser()
    args = parser.parse_args()
    exit_code = asyncio.run(_async_main(args))
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
