"""
TS-UD-WBS-001 - WBS Item Entity Domain Tests

Test Suite ID: TS-UD-WBS-001
Component: WBS Module - Domain Entities
Priority: P1
Phase: RED (Write failing tests first)

Domain unit tests for WBSItem entity and value objects.
These tests will FAIL until the domain logic is fully implemented.

Run: pytest tests/modules/wbs/domain/test_wbs_item_entity.py -v
"""

import pytest
from uuid import UUID, uuid4
from datetime import date

from src.wbs.domain.entities import WBSItem, Money


# ===========================================
# TESTS: WBSItem Creation with Valid Code
# ===========================================


class TestWBSItemCreation:
    """Tests for WBSItem creation and validation."""

    def test_create_wbs_item_with_valid_code(self):
        """
        RED Phase: Create WBS item with valid code format.
        
        Valid codes: "1", "1.1", "1.1.1", "1.1.1.1"
        Expected: WBSItem created successfully with correct attributes
        """
        # Arrange
        project_id = "test-project-001"
        tenant_id = "test-tenant-001"
        name = "Foundation Works"
        code = "1.2.3"
        
        # Act
        item = WBSItem.create(
            project_id=project_id,
            tenant_id=tenant_id,
            name=name,
            code=code,
        )
        
        # Assert
        assert isinstance(item, WBSItem)
        assert item.project_id == project_id
        assert item.tenant_id == tenant_id
        assert item.name == name
        assert item.code == code
        assert item.level == 3  # "1.2.3" has 3 levels
        assert isinstance(item.id, UUID)

    def test_create_wbs_item_with_invalid_code_raises_error(self):
        """
        RED Phase: Invalid code format should raise ValueError.
        
        Invalid codes: "A.1", "1..1", "1.1.1.1.1", "-1"
        Expected: ValueError raised with descriptive message
        """
        invalid_codes = [
            "A.1",          # Contains letters
            "1..1",         # Double dot
            "1.1.1.1.1",    # Too deep (level 5)
            "-1",           # Negative
            "1.1.",         # Trailing dot
        ]
        
        for code in invalid_codes:
            with pytest.raises(ValueError) as exc_info:
                WBSItem.create(
                    project_id="test-project-001",
                    tenant_id="test-tenant-001",
                    name="Test Item",
                    code=code,
                )
            
            assert "code" in str(exc_info.value).lower(), (
                f"Error message should mention 'code' for invalid code: {code}"
            )

    def test_code_level_consistency(self):
        """
        RED Phase: Code depth must match level attribute.
        
        Expected: Level = number of dot-separated parts in code
        """
        test_cases = [
            ("1", 1),
            ("1.1", 2),
            ("1.1.1", 3),
            ("1.1.1.1", 4),
        ]
        
        for code, expected_level in test_cases:
            item = WBSItem.create(
                project_id="test-project-001",
                tenant_id="test-tenant-001",
                name=f"Level {expected_level} Item",
                code=code,
            )
            
            assert item.level == expected_level, (
                f"Code '{code}' should have level {expected_level}, got {item.level}"
            )


# ===========================================
# TESTS: Code Generation (Note: Code generation is a use case concern)
# ===========================================


class TestWBSCodeGeneration:
    """
    Tests for automatic code generation.
    
    NOTE: Code generation requires repository access to check existing codes.
    These tests verify the entity accepts auto-generated codes correctly.
    Actual generation logic belongs in CreateWBSItemUseCase.
    """

    def test_generate_code_for_root_item(self):
        """
        RED Phase: Entity accepts auto-generated root codes.
        
        When use case generates "1", "2", "3", entity should accept them.
        Expected: Entity created with provided code
        """
        project_id = "test-project-001"
        tenant_id = "test-tenant-001"
        
        # Simulate use case generating sequential codes
        item1 = WBSItem.create(
            project_id=project_id,
            tenant_id=tenant_id,
            name="First Root Item",
            code="1",  # Generated by use case
        )
        
        assert item1.code == "1"
        assert item1.level == 1
        
        item2 = WBSItem.create(
            project_id=project_id,
            tenant_id=tenant_id,
            name="Second Root Item",
            code="2",  # Generated by use case
        )
        
        assert item2.code == "2"
        assert item2.level == 1

    def test_generate_code_for_child_item(self):
        """
        RED Phase: Entity accepts auto-generated child codes.
        
        When use case generates "1.1", "1.2", entity should accept them.
        Expected: Entity created with provided code and correct level
        """
        project_id = "test-project-001"
        tenant_id = "test-tenant-001"
        
        # Create parent
        parent = WBSItem.create(
            project_id=project_id,
            tenant_id=tenant_id,
            name="Parent Item",
            code="1",
        )
        
        # Simulate use case generating child code
        child1 = WBSItem.create(
            project_id=project_id,
            tenant_id=tenant_id,
            name="First Child",
            code="1.1",  # Generated by use case based on parent.code
            parent_id=parent.id,
        )
        
        assert child1.code == "1.1"
        assert child1.level == 2


# ===========================================
# TESTS: Depth and Validation Constraints
# ===========================================


class TestWBSValidationConstraints:
    """Tests for validation constraints."""

    def test_cannot_exceed_maximum_depth(self):
        """
        RED Phase: Maximum WBS depth is 4 levels.
        
        Level 5 code "1.1.1.1.1" should raise ValueError
        Expected: ValueError with message about maximum depth
        """
        with pytest.raises(ValueError) as exc_info:
            WBSItem.create(
                project_id="test-project-001",
                tenant_id="test-tenant-001",
                name="Too Deep Item",
                code="1.1.1.1.1",  # Level 5 - too deep
            )
        
        error_msg = str(exc_info.value).lower()
        assert "level" in error_msg or "depth" in error_msg or "maximum" in error_msg, (
            f"Error should mention level/depth/maximum, got: {error_msg}"
        )

    def test_completion_percentage_validation(self):
        """
        RED Phase: Completion must be between 0 and 100.
        
        Expected: ValueError for < 0 or > 100
        """
        invalid_completions = [-1, -5, 101, 150]
        
        for completion in invalid_completions:
            with pytest.raises(ValueError) as exc_info:
                WBSItem.create(
                    project_id="test-project-001",
                    tenant_id="test-tenant-001",
                    name="Test Item",
                    code="1",
                    completion=completion,
                )
            
            assert "completion" in str(exc_info.value).lower(), (
                f"Error should mention 'completion' for invalid value: {completion}"
            )


# ===========================================
# TESTS: Money Value Object
# ===========================================


class TestMoneyValueObject:
    """Tests for Money value object."""

    def test_budget_money_value_object(self):
        """
        RED Phase: Money value object validation.
        
        Expected: 
        - Negative amounts raise ValueError
        - Invalid currency (not 3 chars) raises ValueError
        """
        # Test negative amount
        with pytest.raises(ValueError) as exc_info:
            Money(amount=-1000.0, currency="EUR")
        
        assert "negative" in str(exc_info.value).lower(), (
            "Error should mention 'negative' for negative amount"
        )
        
        # Test invalid currency
        with pytest.raises(ValueError) as exc_info:
            Money(amount=1000.0, currency="EURO")  # 4 chars - invalid
        
        assert "currency" in str(exc_info.value).lower(), (
            "Error should mention 'currency' for invalid currency code"
        )
        
        # Test valid Money creation
        money = Money(amount=450000.0, currency="EUR")
        assert money.amount == 450000.0
        assert money.currency == "EUR"


# ===========================================
# TESTS: Immutability
# ===========================================


class TestWBSImmutability:
    """Tests for WBSItem immutability."""

    def test_wbs_item_immutability(self):
        """
        RED Phase: WBSItem entity should be immutable (frozen).
        
        Expected: dataclass(frozen=True) prevents attribute modification
        """
        item = WBSItem.create(
            project_id="test-project-001",
            tenant_id="test-tenant-001",
            name="Immutable Item",
            code="1",
        )
        
        # Attempt to modify should raise FrozenInstanceError
        with pytest.raises((AttributeError, TypeError)):
            item.name = "Modified Name"
        
        with pytest.raises((AttributeError, TypeError)):
            item.completion = 50


# ===========================================
# TESTS: Ancestor Relationship
# ===========================================


class TestWBSAncestorRelationship:
    """Tests for ancestor/descendant relationships."""

    def test_is_ancestor_of(self):
        """
        RED Phase: Check ancestor relationship between items.
        
        Expected:
        - item1 ("1") is ancestor of item1_1 ("1.1")
        - item1_1 ("1.1") is NOT ancestor of item1 ("1")
        - item2 ("2") is NOT ancestor of item1_1 ("1.1")
        """
        # Create hierarchy
        root = WBSItem.create(
            project_id="test-project-001",
            tenant_id="test-tenant-001",
            name="Root",
            code="1",
        )
        
        child = WBSItem.create(
            project_id="test-project-001",
            tenant_id="test-tenant-001",
            name="Child",
            code="1.1",
            parent_id=root.id,
        )
        
        grandchild = WBSItem.create(
            project_id="test-project-001",
            tenant_id="test-tenant-001",
            name="Grandchild",
            code="1.1.1",
            parent_id=child.id,
        )
        
        # Test ancestor relationships
        assert root.is_ancestor_of(child), (
            "Root should be ancestor of child"
        )
        assert root.is_ancestor_of(grandchild), (
            "Root should be ancestor of grandchild"
        )
        assert child.is_ancestor_of(grandchild), (
            "Child should be ancestor of grandchild"
        )
        
        # Test non-ancestor relationships
        assert not child.is_ancestor_of(root), (
            "Child should NOT be ancestor of root"
        )
        assert not grandchild.is_ancestor_of(root), (
            "Grandchild should NOT be ancestor of root"
        )
        assert not grandchild.is_ancestor_of(child), (
            "Grandchild should NOT be ancestor of child"
        )


# ===========================================
# END OF TEST SUITE
# ===========================================

# Mark all tests in this file as unit tests
# Note: 7/10 tests passing from previous GREEN phase
# 3 tests (code generation) need implementation
pytestmark = [
    pytest.mark.unit,
    pytest.mark.red_phase,
]
