"""
Schemathesis contract-test fixtures — TASK-QA-200.

Design:
- Load schema offline from docs/api/openapi.yaml (no live server needed).
- Test via ASGI transport: case.call_asgi(app=contract_app).
- Auth: override get_current_user_id dependency; also inject a valid JWT for
  routes that inspect the header directly.
- Multi-tenant: inject X-Tenant-ID header from a fixed test-tenant UUID.
- Mocked boundaries: C2PRO_AI_MOCK=1, Langsmith/Langchain patched by the
  global isolate_langsmith_and_langchain_sdks autouse fixture (sdk_isolators.py).
- Coverage: session-level hooks write contract-coverage.json on session end.
"""

from __future__ import annotations

import json
import os
from datetime import UTC, datetime, timedelta
from pathlib import Path
from uuid import UUID

import jwt
import pytest
from fastapi import FastAPI

# ---------------------------------------------------------------------------
# Fixed synthetic identities (no DB required for contract tests)
# ---------------------------------------------------------------------------

TENANT_ID: UUID = UUID("c0000001-0000-0000-0000-000000000001")
USER_ID: UUID = UUID("c0000001-0000-0000-0000-000000000002")

_JWT_SECRET: str = os.environ.get(
    "JWT_SECRET_KEY",
    "test-secret-key-min-32-chars-required-for-testing-purposes-only",
)
_JWT_ALGO: str = os.environ.get("JWT_ALGORITHM", "HS256")

# Path to the canonical OpenAPI spec (generated by apps/api/scripts/generate_openapi.py)
SCHEMA_PATH: Path = (
    Path(__file__).resolve().parents[5] / "docs" / "api" / "openapi.yaml"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def mint_contract_jwt() -> str:
    """Mint a short-lived JWT for the fixed contract-test identity."""
    payload = {
        "sub": str(USER_ID),
        "tenant_id": str(TENANT_ID),
        "email": "contract-test@c2pro.test",
        "role": "admin",
        "exp": datetime.now(UTC) + timedelta(hours=2),
        "iat": datetime.now(UTC),
        "type": "access",
    }
    return jwt.encode(payload, _JWT_SECRET, algorithm=_JWT_ALGO)


def create_contract_app() -> FastAPI:
    """Create the ASGI app with auth dependency overridden for contract tests."""
    os.environ.setdefault("C2PRO_AI_MOCK", "1")

    from src.core.security import get_current_user_id
    from src.main import create_application

    app = create_application()
    # Skip real JWT validation — return the fixed contract-test user ID.
    app.dependency_overrides[get_current_user_id] = lambda: USER_ID
    return app


# ---------------------------------------------------------------------------
# Module-scoped fixtures (one app + token per test file, not per case)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def contract_app() -> FastAPI:
    """ASGI app with auth bypassed for contract tests."""
    return create_contract_app()


@pytest.fixture(scope="module")
def contract_jwt() -> str:
    """JWT for the contract-test user."""
    return mint_contract_jwt()


@pytest.fixture(scope="module")
def contract_headers(contract_jwt: str) -> dict[str, str]:
    """HTTP headers injected into every Schemathesis case."""
    return {
        "Authorization": f"Bearer {contract_jwt}",
        "X-Tenant-ID": str(TENANT_ID),
    }


# ---------------------------------------------------------------------------
# Coverage tracker (session-level pytest hooks)
# ---------------------------------------------------------------------------

_SESSION_COVERED: set[str] = set()
_SESSION_ALL_PATHS: set[str] = set()


def _extract_openapi_paths() -> set[str]:
    """Collect all operation paths from the OpenAPI yaml."""
    if not SCHEMA_PATH.exists():
        return set()
    try:
        import schemathesis

        schema = schemathesis.from_path(str(SCHEMA_PATH), base_url="http://testserver")
        paths: set[str] = set()
        for endpoint in schema.get_all_operations():
            if hasattr(endpoint, "path"):
                paths.add(endpoint.path)
        return paths
    except Exception:
        return set()


def pytest_collection_finish(session: pytest.Session) -> None:
    global _SESSION_ALL_PATHS  # noqa: PLW0603
    _SESSION_ALL_PATHS = _extract_openapi_paths()


def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    """Track paths exercised by Schemathesis cases (encoded in node IDs)."""
    if report.when != "call":
        return
    # Schemathesis encodes path+method in test ID: "test_foo[GET /health/live]"
    node_id = getattr(report, "nodeid", "")
    if "[" in node_id and "]" in node_id:
        fragment = node_id[node_id.index("[") + 1 : node_id.rindex("]")]
        parts = fragment.split(" ", 1)
        if len(parts) == 2:
            _SESSION_COVERED.add(parts[1])


def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Write contract-coverage.json when the session completes."""
    if not _SESSION_ALL_PATHS and not _SESSION_COVERED:
        return

    covered = _SESSION_COVERED & _SESSION_ALL_PATHS
    uncovered = _SESSION_ALL_PATHS - _SESSION_COVERED
    total = len(_SESSION_ALL_PATHS)
    coverage_pct = round(len(covered) / total * 100, 1) if total > 0 else 0.0

    report = {
        "generated_at": datetime.now(UTC).isoformat(),
        "schema_path": str(SCHEMA_PATH),
        "total_operations": total,
        "covered_operations": len(covered),
        "coverage_pct": coverage_pct,
        "covered": sorted(covered),
        "uncovered": sorted(uncovered),
    }

    out_path = Path(__file__).parents[3] / "contract-coverage.json"
    try:
        out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    except OSError:
        pass
