"""
TASK-QA-203: Schemathesis contract tests — WBS / Procurement router.

Covers all operations under /api/v1/procurement/* and /api/v1/assignments.
Replaces: TASK-QA-058..062 (partial — WBS/BOM surface only).

Notes:
- BOM/WBS operations require authentication (contract_headers injected).
- /api/v1/procurement/wbs and /api/v1/procurement/bom share this suite.
- /api/v1/assignments covers RACI assignment operations.
- POST endpoints that create items may return 404 for non-existent project_ids
  (generated by schemathesis) — 404 is a documented response and considered valid.
"""

from __future__ import annotations

import pytest

import schemathesis
from tests.contract.schemathesis.conftest import SCHEMA_PATH

pytestmark = [pytest.mark.contract]

if not SCHEMA_PATH.exists():
    pytest.skip("OpenAPI schema not found — run `make openapi` first.", allow_module_level=True)

_SCHEMA = schemathesis.from_path(str(SCHEMA_PATH), base_url="http://testserver")
_WBS_PROCUREMENT_SCHEMA = _SCHEMA.include(
    path_regex=r"^/api/v1/(procurement|assignments)"
)


@_WBS_PROCUREMENT_SCHEMA.parametrize()
def test_wbs_procurement_contract(
    case: schemathesis.Case, contract_app, contract_headers
) -> None:
    """WBS, BOM, and RACI assignment endpoints return responses conforming to OpenAPI spec."""
    response = case.call_asgi(app=contract_app, headers=contract_headers)
    case.validate_response(response)
