"""
TASK-QA-203: Schemathesis contract tests — WBS / RACI router.

Covers public WBS item operations under /api/v1/projects/{project_id}/wbs/items*
and the RACI assignment surface under /api/v1/assignments.
Replaces: TASK-QA-058..062 (partial — WBS/BOM surface only).

Notes:
- BOM/WBS operations require authentication (contract_headers injected).
- /api/v1/projects/{project_id}/wbs/items* is the current item-level WBS
  HTTP surface that is testable without a seeded projects DB.
- /api/v1/assignments covers RACI assignment operations when present in the schema.
- POST endpoints that create items may return 404 for non-existent project_ids
  (generated by schemathesis) — 404 is a documented response and considered valid.
"""

from __future__ import annotations

import pytest
from starlette_testclient import TestClient

import schemathesis
from schemathesis import GenerationMode
from schemathesis.config import (
    ChecksConfig,
    GenerationConfig,
    ProjectConfig,
    ProjectsConfig,
    SchemathesisConfig,
    SimpleCheckConfig,
)
from schemathesis.core import NotSet
from tests.contract.schemathesis.conftest import SCHEMA_PATH

pytestmark = [pytest.mark.contract]

if not SCHEMA_PATH.exists():
    pytest.skip("OpenAPI schema not found — run `make openapi` first.", allow_module_level=True)

_CONFIG = SchemathesisConfig(
    projects=ProjectsConfig(
        default=ProjectConfig(
            checks=ChecksConfig(
                # This contract injects a known-good local JWT after generation.
                # Keep response/schema checks active, but ignore generated invalid-auth metadata.
                ignored_auth=SimpleCheckConfig(enabled=False),
            ),
            generation=GenerationConfig(
                modes=[GenerationMode.POSITIVE],
                max_examples=1,
                deterministic=True,
            ),
        ),
    ),
)
_SCHEMA = schemathesis.from_path(
    str(SCHEMA_PATH),
    base_url="https://testserver",
    config=_CONFIG,
)
_WBS_PROCUREMENT_SCHEMA = _SCHEMA.include(
    path_regex=r"^/api/v1/(projects/[^/]+/wbs/items|assignments)",
    tag_regex=r"^(wbs|assignments)$",
)


@_WBS_PROCUREMENT_SCHEMA.parametrize()
def test_wbs_procurement_contract(
    case: schemathesis.Case, contract_app, contract_headers
) -> None:
    """WBS, BOM, and RACI assignment endpoints return responses conforming to OpenAPI spec."""
    request_kwargs = {"headers": {**(case.headers or {}), **contract_headers}}
    if case.query:
        request_kwargs["params"] = case.query
    if not isinstance(case.body, NotSet):
        request_kwargs["json"] = case.body

    with TestClient(contract_app) as client:
        response = client.request(case.method, case.formatted_path, **request_kwargs)
    case.validate_response(response)
