"""Defines the Pydantic model for Coherence-related LangSmith span attributes."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# A set of all allowed attribute keys for quick validation.
# This is the single source of truth for the EU-residency-safe attribute allowlist.
COHERENCE_SPAN_ATTRIBUTE_ALLOWLIST = {
    "coherence.node_name",
    "coherence.score_version",
    "coherence.findings_count",
    "coherence.rule_ids",
    "coherence.tenant_id",
    "coherence.project_id",
    "coherence.alert.rule_id",
    "coherence.alert.severity",
}


class CoherenceSpanAttributes(BaseModel):
    """
    A Pydantic model representing the allowlisted attributes for Coherence-related spans.
    This model ensures that only non-sensitive, EU-residency-safe data is attached to spans.
    """

    node_name: str = Field(..., description="The name of the graph node being executed.")
    score_version: Literal["v0", "v1"] = Field(
        ..., description="The version of the scoring logic being used."
    )
    findings_count: int | None = Field(
        None, description="The number of findings generated by the node."
    )
    rule_ids: list[str] | None = Field(
        None, description="A list of rule IDs evaluated by the node."
    )
    tenant_id: str = Field(..., description="The ID of the tenant.")
    project_id: str = Field(..., description="The ID of the project.")


class CoherenceAlertSpanAttributes(BaseModel):
    """
    Attributes for spans specifically marking the creation of a high-priority alert.
    """

    rule_id: str = Field(..., alias="coherence.alert.rule_id")
    severity: str = Field(..., alias="coherence.alert.severity")

