@echo off
REM CE-21: Migration Script Preparation & Validation
REM Validates migration scripts before execution

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..\..
set LOG_DIR=%PROJECT_ROOT%\logs
set MIGRATIONS_DIR=%PROJECT_ROOT%\infrastructure\supabase\migrations

echo ==================================
echo CE-21: Script Validation
echo ==================================
echo Started at: %date% %time%
echo.

REM Load environment variables
if exist "%PROJECT_ROOT%\.env.staging" (
    for /f "usebackq tokens=*" %%a in ("%PROJECT_ROOT%\.env.staging") do set %%a
) else (
    for /f "usebackq tokens=*" %%a in ("%PROJECT_ROOT%\.env") do set %%a
)

REM 1. List all migration files
echo --- Step 1: Review Migration Files ---
dir /b "%MIGRATIONS_DIR%\*.sql"
echo.

REM 2. Validate SQL syntax (dry-run with psql)
echo --- Step 2: Validate SQL Syntax ---
echo NOTE: This requires manual review or PostgreSQL syntax checker
echo Review migration files in: %MIGRATIONS_DIR%
echo.

REM 3. Dry-run migration
echo --- Step 3: Dry-Run Migration ---
python "%PROJECT_ROOT%\infrastructure\supabase\run_migrations.py" --env staging --dry-run --verbose > "%LOG_DIR%\ce21_dry_run.log" 2>&1
if %errorlevel% equ 0 (
    echo √ Dry-run successful
    type "%LOG_DIR%\ce21_dry_run.log"
) else (
    echo × Dry-run failed
    type "%LOG_DIR%\ce21_dry_run.log"
    exit /b 1
)

REM 4. Generate report
echo.
echo --- Step 4: Generate Validation Report ---
(
echo # Migration Script Validation Report
echo **Date**: %date% %time%
echo **Task**: CE-21 Script Validation
echo.
echo ## Validation Results
echo √ Migration files found
echo √ Dry-run completed successfully
echo.
echo ## Migration Files
dir /b "%MIGRATIONS_DIR%\*.sql"
echo.
echo ## Dry-Run Log
echo See: `%LOG_DIR%\ce21_dry_run.log`
echo.
echo ## Next Steps
echo - Proceed to CE-22: Execute Migrations
echo.
echo ---
echo Generated by CE-21 validation script
) > "%PROJECT_ROOT%\docs\migration_execution_plan.md"

echo √ Validation report generated
echo.
echo ==================================
echo CE-21 Validation Complete!
echo ==================================
echo Status: READY FOR CE-22
echo Completed at: %date% %time%

endlocal
