@echo off
REM CE-23: RLS Policy Verification
REM Verifies Row Level Security policies are working

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..\..
set LOG_DIR=%PROJECT_ROOT%\logs

echo ==================================
echo CE-23: RLS Verification
echo ==================================
echo Started at: %date% %time%
echo.

REM Load environment variables
if exist "%PROJECT_ROOT%\.env.staging" (
    for /f "usebackq tokens=*" %%a in ("%PROJECT_ROOT%\.env.staging") do set %%a
)

REM 1. Check RLS coverage
echo --- Step 1: Check RLS Coverage ---
psql "%DATABASE_URL%" -f "%SCRIPT_DIR%\verify_rls_coverage.sql" > "%LOG_DIR%\ce23_rls_coverage.log" 2>&1
type "%LOG_DIR%\ce23_rls_coverage.log"

REM 2. Run automated RLS tests
echo.
echo --- Step 2: Run Automated RLS Tests ---
cd "%PROJECT_ROOT%\apps\api"
pytest tests\verification\test_gate1_rls.py -v --tb=short --log-file="%LOG_DIR%\ce23_rls_tests.log" 2>&1 | tee "%LOG_DIR%\ce23_rls_tests_console.log"

if %errorlevel% equ 0 (
    echo.
    echo √ All RLS tests passed

    REM Generate report
    (
    echo # RLS Verification Report
    echo **Date**: %date% %time%
    echo **Task**: CE-23 RLS Verification
    echo.
    echo ## Results
    echo √ RLS coverage verified
    echo √ All automated tests passed
    echo.
    echo ## Logs
    echo - Coverage: `%LOG_DIR%\ce23_rls_coverage.log`
    echo - Tests: `%LOG_DIR%\ce23_rls_tests.log`
    echo.
    echo ---
    echo Generated by CE-23 verification script
    ) > "%PROJECT_ROOT%\docs\ce23_rls_verification_report.md"

    echo.
    echo ==================================
    echo CE-23 RLS Verification Complete!
    echo ==================================
    echo Status: READY FOR CE-24
    echo Completed at: %date% %time%
) else (
    echo.
    echo × RLS tests FAILED
    echo Check logs: %LOG_DIR%\ce23_*.log
    exit /b 1
)

cd "%SCRIPT_DIR%"
endlocal
