@echo off
REM CE-24: Foreign Key Constraint Verification
REM Verifies foreign key constraints are properly configured

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..\..
set LOG_DIR=%PROJECT_ROOT%\logs

echo ==================================
echo CE-24: FK Verification
echo ==================================
echo Started at: %date% %time%
echo.

REM Load environment variables
if exist "%PROJECT_ROOT%\.env.staging" (
    for /f "usebackq tokens=*" %%a in ("%PROJECT_ROOT%\.env.staging") do set %%a
)

REM 1. List all foreign keys
echo --- Step 1: List All Foreign Keys ---
psql "%DATABASE_URL%" -f "%SCRIPT_DIR%\list_foreign_keys.sql" > "%LOG_DIR%\ce24_fk_list.log" 2>&1
type "%LOG_DIR%\ce24_fk_list.log"

REM 2. Check for orphaned records
echo.
echo --- Step 2: Check for Orphaned Records ---
psql "%DATABASE_URL%" -f "%SCRIPT_DIR%\check_orphaned_records.sql" > "%LOG_DIR%\ce24_orphan_check.log" 2>&1
type "%LOG_DIR%\ce24_orphan_check.log"

REM 3. Test FK integrity
echo.
echo --- Step 3: Test FK Integrity ---
psql "%DATABASE_URL%" -f "%SCRIPT_DIR%\test_fk_integrity.sql" > "%LOG_DIR%\ce24_fk_integrity.log" 2>&1
type "%LOG_DIR%\ce24_fk_integrity.log"

if %errorlevel% equ 0 (
    echo.
    echo √ All FK verification checks passed

    REM Generate report
    (
    echo # Foreign Key Verification Report
    echo **Date**: %date% %time%
    echo **Task**: CE-24 FK Verification
    echo.
    echo ## Results
    echo √ All foreign keys verified
    echo √ No orphaned records found
    echo √ FK integrity tests passed
    echo.
    echo ## Logs
    echo - FK List: `%LOG_DIR%\ce24_fk_list.log`
    echo - Orphan Check: `%LOG_DIR%\ce24_orphan_check.log`
    echo - Integrity: `%LOG_DIR%\ce24_fk_integrity.log`
    echo.
    echo ---
    echo Generated by CE-24 verification script
    ) > "%PROJECT_ROOT%\docs\ce24_foreign_key_report.md"

    echo.
    echo ==================================
    echo CE-24 FK Verification Complete!
    echo ==================================
    echo Status: READY FOR CE-25
    echo Completed at: %date% %time%
) else (
    echo.
    echo × FK verification FAILED
    echo Check logs: %LOG_DIR%\ce24_*.log
    exit /b 1
)

endlocal
