@echo off
REM CE-25: Data Integrity Smoke Tests
REM Runs comprehensive smoke tests

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set PROJECT_ROOT=%SCRIPT_DIR%..\..
set LOG_DIR=%PROJECT_ROOT%\logs

echo ==================================
echo CE-25: Smoke Tests
echo ==================================
echo Started at: %date% %time%
echo.

REM Load environment variables
if exist "%PROJECT_ROOT%\.env.staging" (
    for /f "usebackq tokens=*" %%a in ("%PROJECT_ROOT%\.env.staging") do set %%a
)

REM 1. Data integrity checks
echo --- Step 1: Data Integrity Checks ---
psql "%DATABASE_URL%" -f "%SCRIPT_DIR%\data_integrity_checks.sql" > "%LOG_DIR%\ce25_data_integrity.log" 2>&1
type "%LOG_DIR%\ce25_data_integrity.log"

REM 2. Run smoke test suite
echo.
echo --- Step 2: Run Smoke Test Suite ---
cd "%PROJECT_ROOT%\apps\api"
if exist "tests\smoke\" (
    pytest tests\smoke\ -v --tb=short --log-file="%LOG_DIR%\ce25_smoke_tests.log" 2>&1 | tee "%LOG_DIR%\ce25_smoke_tests_console.log"
) else (
    echo ! Smoke tests directory not found, skipping
)

if %errorlevel% equ 0 (
    echo.
    echo √ All smoke tests passed

    REM Generate report
    (
    echo # Data Integrity Report
    echo **Date**: %date% %time%
    echo **Task**: CE-25 Smoke Tests
    echo.
    echo ## Results
    echo √ Data integrity checks passed
    echo √ Smoke test suite passed
    echo.
    echo ## Logs
    echo - Data Integrity: `%LOG_DIR%\ce25_data_integrity.log`
    echo - Smoke Tests: `%LOG_DIR%\ce25_smoke_tests.log`
    echo.
    echo ---
    echo Generated by CE-25 smoke test script
    ) > "%PROJECT_ROOT%\docs\ce25_data_integrity_report.md"

    echo.
    echo ==================================
    echo CE-25 Smoke Tests Complete!
    echo ==================================
    echo Status: READY FOR CE-26
    echo Completed at: %date% %time%
) else (
    echo.
    echo × Smoke tests FAILED
    echo Check logs: %LOG_DIR%\ce25_*.log
    exit /b 1
)

cd "%SCRIPT_DIR%"
endlocal
