-- =====================================================
-- Migration: 20260318000100_add_stakeholders_tables.sql
-- Date: 2026-03-18
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'racirole') THEN
        CREATE TYPE racirole AS ENUM ('R', 'A', 'C', 'I');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.stakeholder_wbs_raci (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	stakeholder_id UUID NOT NULL, 
	wbs_item_id UUID NOT NULL, 
	raci_role racirole NOT NULL, 
	evidence_text TEXT, 
	generated_automatically BOOLEAN NOT NULL, 
	manually_verified BOOLEAN NOT NULL, 
	verified_by UUID, 
	verified_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE,
	FOREIGN KEY(wbs_item_id) REFERENCES public.procurement_wbs_items (id) ON DELETE CASCADE,
	FOREIGN KEY(verified_by) REFERENCES public.users (id)
)


;
CREATE INDEX IF NOT EXISTS ix_stakeholder_wbs_raci_wbs_item_id ON public.stakeholder_wbs_raci (wbs_item_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholder_wbs_raci_raci_role ON public.stakeholder_wbs_raci (raci_role)
;
CREATE INDEX IF NOT EXISTS ix_stakeholder_wbs_raci_tenant_id ON public.stakeholder_wbs_raci (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholder_wbs_raci_project_id ON public.stakeholder_wbs_raci (project_id)
;
CREATE INDEX IF NOT EXISTS ix_raci_stakeholder ON public.stakeholder_wbs_raci (stakeholder_id)
;
CREATE INDEX IF NOT EXISTS ix_raci_wbs ON public.stakeholder_wbs_raci (wbs_item_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholder_wbs_raci_stakeholder_id ON public.stakeholder_wbs_raci (stakeholder_id)
;
CREATE INDEX IF NOT EXISTS ix_raci_tenant ON public.stakeholder_wbs_raci (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_raci_role ON public.stakeholder_wbs_raci (raci_role)
;

-- ========================================================;

ALTER TABLE public.stakeholder_wbs_raci ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stakeholder_wbs_raci FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stakeholder_wbs_raci_tenant_isolation_select ON public.stakeholder_wbs_raci;
CREATE POLICY stakeholder_wbs_raci_tenant_isolation_select ON public.stakeholder_wbs_raci
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholder_wbs_raci_tenant_isolation_insert ON public.stakeholder_wbs_raci;
CREATE POLICY stakeholder_wbs_raci_tenant_isolation_insert ON public.stakeholder_wbs_raci
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholder_wbs_raci_tenant_isolation_update ON public.stakeholder_wbs_raci;
CREATE POLICY stakeholder_wbs_raci_tenant_isolation_update ON public.stakeholder_wbs_raci
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholder_wbs_raci_tenant_isolation_delete ON public.stakeholder_wbs_raci;
CREATE POLICY stakeholder_wbs_raci_tenant_isolation_delete ON public.stakeholder_wbs_raci
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'powerlevel') THEN
        CREATE TYPE powerlevel AS ENUM ('low', 'medium', 'high');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'interestlevel') THEN
        CREATE TYPE interestlevel AS ENUM ('low', 'medium', 'high');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'stakeholderquadrant') THEN
        CREATE TYPE stakeholderquadrant AS ENUM ('key_player', 'keep_satisfied', 'keep_informed', 'monitor');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.stakeholders (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	name VARCHAR(255), 
	role VARCHAR(100), 
	organization VARCHAR(255), 
	department VARCHAR(100), 
	power_level powerlevel NOT NULL, 
	interest_level interestlevel NOT NULL, 
	quadrant stakeholderquadrant, 
	email VARCHAR(255), 
	phone VARCHAR(50), 
	source_clause_id UUID, 
	extracted_from_document_id UUID, 
	approval_status approvalstatus NOT NULL, 
	reviewed_by UUID, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	review_comment TEXT, 
	stakeholder_metadata JSONB NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(source_clause_id) REFERENCES public.clauses (id), 
	FOREIGN KEY(extracted_from_document_id) REFERENCES public.documents (id), 
	FOREIGN KEY(reviewed_by) REFERENCES public.users (id)
)


;
CREATE INDEX IF NOT EXISTS ix_stakeholders_approval_status ON public.stakeholders (approval_status)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_source_clause_id ON public.stakeholders (source_clause_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_project_id ON public.stakeholders (project_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_quadrant ON public.stakeholders (quadrant)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_tenant ON public.stakeholders (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_tenant_id ON public.stakeholders (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_clause ON public.stakeholders (source_clause_id)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_email ON public.stakeholders (email)
;
CREATE INDEX IF NOT EXISTS ix_stakeholders_project ON public.stakeholders (project_id)
;

-- ========================================================;

ALTER TABLE public.stakeholders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stakeholders FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stakeholders_tenant_isolation_select ON public.stakeholders;
CREATE POLICY stakeholders_tenant_isolation_select ON public.stakeholders
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholders_tenant_isolation_insert ON public.stakeholders;
CREATE POLICY stakeholders_tenant_isolation_insert ON public.stakeholders
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholders_tenant_isolation_update ON public.stakeholders;
CREATE POLICY stakeholders_tenant_isolation_update ON public.stakeholders
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS stakeholders_tenant_isolation_delete ON public.stakeholders;
CREATE POLICY stakeholders_tenant_isolation_delete ON public.stakeholders
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

-- Deferred FK: stakeholders is created later in this file.
ALTER TABLE public.stakeholder_wbs_raci
    ADD CONSTRAINT fk_stakeholder_wbs_raci_stakeholder_id
    FOREIGN KEY (stakeholder_id) REFERENCES public.stakeholders (id) ON DELETE CASCADE;
