-- =====================================================
-- Migration: 20260310000100_add_documents_tables.sql
-- Date: 2026-03-10
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'clausetype') THEN
        CREATE TYPE clausetype AS ENUM (
            'general',
            'technical',
            'legal',
            'financial',
            'administrative',
            'scope',
            'penalty',
            'warranty',
            'payment',
            'delivery',
            'other'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.clauses (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	clause_code VARCHAR(50) NOT NULL, 
	clause_type clausetype, 
	title VARCHAR(255), 
	full_text TEXT, 
	text_start_offset INTEGER, 
	text_end_offset INTEGER, 
	extracted_entities JSONB NOT NULL, 
	extraction_confidence FLOAT, 
	extraction_model VARCHAR(50), 
	manually_verified BOOLEAN NOT NULL, 
	verified_by UUID, 
	verified_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(document_id) REFERENCES public.documents (id) ON DELETE CASCADE, 
	FOREIGN KEY(verified_by) REFERENCES public.users (id)
)


;
CREATE INDEX IF NOT EXISTS ix_clauses_project_id ON public.clauses (project_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_project ON public.clauses (project_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_verified ON public.clauses (manually_verified, verified_at)
;
CREATE INDEX IF NOT EXISTS ix_clauses_document_id ON public.clauses (document_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_document ON public.clauses (document_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_tenant ON public.clauses (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_tenant_id ON public.clauses (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_clauses_type ON public.clauses (clause_type)
;
CREATE INDEX IF NOT EXISTS ix_clauses_code ON public.clauses (clause_code)
;
CREATE INDEX IF NOT EXISTS ix_clauses_clause_code ON public.clauses (clause_code)
;
CREATE INDEX IF NOT EXISTS ix_clauses_clause_type ON public.clauses (clause_type)
;

-- ========================================================;

ALTER TABLE public.clauses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clauses FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clauses_tenant_isolation_select ON public.clauses;
CREATE POLICY clauses_tenant_isolation_select ON public.clauses
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clauses_tenant_isolation_insert ON public.clauses;
CREATE POLICY clauses_tenant_isolation_insert ON public.clauses
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clauses_tenant_isolation_update ON public.clauses;
CREATE POLICY clauses_tenant_isolation_update ON public.clauses
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clauses_tenant_isolation_delete ON public.clauses;
CREATE POLICY clauses_tenant_isolation_delete ON public.clauses
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.document_chunks (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	content TEXT NOT NULL, 
	embedding VECTOR(1536) NOT NULL, 
	metadata JSONB DEFAULT '{}' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(document_id) REFERENCES public.documents (id) ON DELETE CASCADE, 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON public.document_chunks (document_id)
;
CREATE INDEX IF NOT EXISTS ix_document_chunks_tenant ON public.document_chunks (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_document_chunks_document ON public.document_chunks (document_id)
;
CREATE INDEX IF NOT EXISTS ix_document_chunks_project_id ON public.document_chunks (project_id)
;
CREATE INDEX IF NOT EXISTS ix_document_chunks_tenant_id ON public.document_chunks (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_document_chunks_project ON public.document_chunks (project_id)
;

-- ========================================================;

ALTER TABLE public.document_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_chunks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS document_chunks_tenant_isolation_select ON public.document_chunks;
CREATE POLICY document_chunks_tenant_isolation_select ON public.document_chunks
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_chunks_tenant_isolation_insert ON public.document_chunks;
CREATE POLICY document_chunks_tenant_isolation_insert ON public.document_chunks
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_chunks_tenant_isolation_update ON public.document_chunks;
CREATE POLICY document_chunks_tenant_isolation_update ON public.document_chunks
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_chunks_tenant_isolation_delete ON public.document_chunks;
CREATE POLICY document_chunks_tenant_isolation_delete ON public.document_chunks
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
