-- =====================================================
-- Migration: 20260603001900_add_category_centroids.sql
-- Date: 2026-06-03
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.category_centroids (
	id UUID NOT NULL, 
	category VARCHAR(50) NOT NULL, 
	embedding_model VARCHAR(100) NOT NULL, 
	score_version INTEGER NOT NULL, 
	embedding VECTOR(1536) NOT NULL, 
	seed_hash VARCHAR(64) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_category_centroids_key UNIQUE (category, embedding_model, score_version)
)


;

-- ========================================================;

ALTER TABLE public.category_centroids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_centroids FORCE ROW LEVEL SECURITY;
-- WARNING: No tenant_id or project_id on category_centroids, fail-closed by default
