-- =====================================================
-- Migration: 20260315000200_add_analysis_and_procurement_tables.sql
-- Date: 2026-03-15
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'alertseverity') THEN
        CREATE TYPE alertseverity AS ENUM ('critical', 'high', 'medium', 'low');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'alertstatus') THEN
        CREATE TYPE alertstatus AS ENUM ('open', 'acknowledged', 'resolved', 'dismissed');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'alerttype') THEN
        CREATE TYPE alerttype AS ENUM ('risk', 'coherence', 'budget', 'wbs');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approvalstatus') THEN
        CREATE TYPE approvalstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CORRECTED');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.alerts (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	analysis_id UUID, 
	severity alertseverity NOT NULL, 
	alert_type alerttype NOT NULL, 
	category VARCHAR(50), 
	rule_id VARCHAR(100), 
	title VARCHAR(255) NOT NULL, 
	message TEXT NOT NULL, 
	description TEXT NOT NULL, 
	recommendation TEXT, 
	source_clause_id UUID, 
	related_clause_ids UUID[], 
	affected_entities JSONB NOT NULL, 
	impact_level VARCHAR(20), 
	alert_metadata JSONB NOT NULL, 
	status alertstatus NOT NULL, 
	approval_status approvalstatus NOT NULL, 
	reviewed_by UUID, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE, 
	review_comment TEXT, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	resolved_by UUID, 
	resolution_notes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE,
	FOREIGN KEY(source_clause_id) REFERENCES public.clauses (id),
	FOREIGN KEY(reviewed_by) REFERENCES public.users (id),
	FOREIGN KEY(resolved_by) REFERENCES public.users (id)
)


;
CREATE INDEX IF NOT EXISTS ix_alerts_tenant_id ON public.alerts (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_alert_type ON public.alerts (alert_type)
;
CREATE INDEX IF NOT EXISTS ix_alerts_status ON public.alerts (status)
;
CREATE INDEX IF NOT EXISTS ix_alerts_clause ON public.alerts (source_clause_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_approval_status ON public.alerts (approval_status)
;
CREATE INDEX IF NOT EXISTS ix_alerts_analysis_id ON public.alerts (analysis_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_created ON public.alerts (created_at)
;
CREATE INDEX IF NOT EXISTS ix_alerts_source_clause_id ON public.alerts (source_clause_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_created_at ON public.alerts (created_at)
;
CREATE INDEX IF NOT EXISTS ix_alerts_project_id ON public.alerts (project_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_project ON public.alerts (project_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_analysis ON public.alerts (analysis_id)
;
CREATE INDEX IF NOT EXISTS ix_alerts_severity ON public.alerts (severity)
;

-- ========================================================;

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS alerts_tenant_isolation_select ON public.alerts;
CREATE POLICY alerts_tenant_isolation_select ON public.alerts
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS alerts_tenant_isolation_insert ON public.alerts;
CREATE POLICY alerts_tenant_isolation_insert ON public.alerts
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS alerts_tenant_isolation_update ON public.alerts;
CREATE POLICY alerts_tenant_isolation_update ON public.alerts
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS alerts_tenant_isolation_delete ON public.alerts;
CREATE POLICY alerts_tenant_isolation_delete ON public.alerts
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'analysistype') THEN
        CREATE TYPE analysistype AS ENUM ('coherence', 'risk', 'cost', 'schedule', 'quality');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'analysisstatus') THEN
        CREATE TYPE analysisstatus AS ENUM ('pending', 'running', 'completed', 'error', 'cancelled');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.analyses (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	analysis_type analysistype NOT NULL, 
	status analysisstatus NOT NULL, 
	result_json JSONB, 
	coherence_score INTEGER, 
	coherence_breakdown JSONB, 
	alerts_count INTEGER NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	completed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS ix_analyses_project_id ON public.analyses (project_id)
;
CREATE INDEX IF NOT EXISTS ix_analyses_created_at ON public.analyses (created_at)
;
CREATE INDEX IF NOT EXISTS ix_analyses_project ON public.analyses (project_id)
;
CREATE INDEX IF NOT EXISTS ix_analyses_tenant_id ON public.analyses (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_analyses_created ON public.analyses (created_at)
;
CREATE INDEX IF NOT EXISTS ix_analyses_status ON public.analyses (status)
;

-- ========================================================;

ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analyses FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS analyses_tenant_isolation_select ON public.analyses;
CREATE POLICY analyses_tenant_isolation_select ON public.analyses
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS analyses_tenant_isolation_insert ON public.analyses;
CREATE POLICY analyses_tenant_isolation_insert ON public.analyses
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS analyses_tenant_isolation_update ON public.analyses;
CREATE POLICY analyses_tenant_isolation_update ON public.analyses
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS analyses_tenant_isolation_delete ON public.analyses;
CREATE POLICY analyses_tenant_isolation_delete ON public.analyses
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.extractions (
	id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	extraction_type VARCHAR(50), 
	data_json JSONB NOT NULL, 
	confidence_score FLOAT, 
	model_version VARCHAR(50), 
	tokens_used INTEGER, 
	cost_usd FLOAT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
	PRIMARY KEY (id)
)


;
CREATE INDEX IF NOT EXISTS ix_extractions_type ON public.extractions (extraction_type)
;
CREATE INDEX IF NOT EXISTS ix_extractions_document_id ON public.extractions (document_id)
;
CREATE INDEX IF NOT EXISTS ix_extractions_document ON public.extractions (document_id)
;
CREATE INDEX IF NOT EXISTS ix_extractions_extraction_type ON public.extractions (extraction_type)
;

-- ========================================================;

ALTER TABLE public.extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.extractions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_extractions ON public.extractions;
CREATE POLICY tenant_isolation_extractions ON public.extractions
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bomcategory') THEN
        CREATE TYPE bomcategory AS ENUM ('material', 'equipment', 'service', 'consumable');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'procurementstatus') THEN
        CREATE TYPE procurementstatus AS ENUM ('pending', 'requested', 'ordered', 'in_transit', 'delivered', 'cancelled');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.procurement_bom_items (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	item_name VARCHAR NOT NULL, 
	quantity DECIMAL(18, 4) NOT NULL, 
	wbs_item_id UUID, 
	item_code VARCHAR, 
	description TEXT, 
	category bomcategory, 
	unit VARCHAR, 
	unit_price DECIMAL(18, 2), 
	total_price DECIMAL(18, 2), 
	currency VARCHAR NOT NULL, 
	supplier VARCHAR, 
	lead_time_days INTEGER, 
	production_time_days INTEGER, 
	transit_time_days INTEGER, 
	incoterm VARCHAR, 
	contract_clause_id UUID, 
 
	budget_item_id UUID, 
	procurement_status procurementstatus NOT NULL, 
	bom_metadata JSONB NOT NULL, 
	PRIMARY KEY (id),
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;

-- ========================================================;

ALTER TABLE public.procurement_bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.procurement_bom_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_procurement_bom_items ON public.procurement_bom_items;
CREATE POLICY tenant_isolation_procurement_bom_items ON public.procurement_bom_items
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

CREATE TABLE IF NOT EXISTS public.procurement_budget_items (
	id UUID NOT NULL, 
	project_id UUID, 
	name VARCHAR NOT NULL, 
	code VARCHAR NOT NULL, 
	amount DECIMAL(18, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	UNIQUE (code)
)


;

-- ========================================================;

ALTER TABLE public.procurement_budget_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.procurement_budget_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_procurement_budget_items ON public.procurement_budget_items;
CREATE POLICY tenant_isolation_procurement_budget_items ON public.procurement_budget_items
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'wbsitemtype') THEN
        CREATE TYPE wbsitemtype AS ENUM ('deliverable', 'work_package', 'activity');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.procurement_wbs_items (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	code VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	level INTEGER NOT NULL, 
	description TEXT, 
	parent_code VARCHAR, 
	item_type wbsitemtype, 
	budget_allocated DECIMAL(18, 2), 
	budget_spent DECIMAL(18, 2) NOT NULL, 
	planned_start TIMESTAMP WITH TIME ZONE, 
	planned_end TIMESTAMP WITH TIME ZONE, 
	actual_start TIMESTAMP WITH TIME ZONE, 
	actual_end TIMESTAMP WITH TIME ZONE, 
	source_clause_id UUID, 
	version INTEGER NOT NULL, 
	wbs_metadata JSONB NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_procurement_wbs_project_code UNIQUE (project_id, code), 
	CONSTRAINT fk_wbs_parent_per_project FOREIGN KEY(project_id, parent_code) REFERENCES public.procurement_wbs_items (project_id, code) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;

-- ========================================================;

ALTER TABLE public.procurement_wbs_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.procurement_wbs_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_procurement_wbs_items ON public.procurement_wbs_items;
CREATE POLICY tenant_isolation_procurement_wbs_items ON public.procurement_wbs_items
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

-- Deferred FKs: added after every table in this file exists, since the
-- generated table order does not follow dependency order.
ALTER TABLE public.alerts
    ADD CONSTRAINT fk_alerts_analysis_id
    FOREIGN KEY (analysis_id) REFERENCES public.analyses (id) ON DELETE CASCADE;

ALTER TABLE public.procurement_bom_items
    ADD CONSTRAINT fk_procurement_bom_items_wbs_item_id
    FOREIGN KEY (wbs_item_id) REFERENCES public.procurement_wbs_items (id);

ALTER TABLE public.procurement_bom_items
    ADD CONSTRAINT fk_procurement_bom_items_budget_item_id
    FOREIGN KEY (budget_item_id) REFERENCES public.procurement_budget_items (id);
