-- =====================================================
-- Migration: 20260319000300_reconcile_and_support_tables.sql
-- Date: 2026-03-19
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.ai_usage_logs (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID, 
	model_name VARCHAR(100) NOT NULL, 
	operation_type VARCHAR(50) NOT NULL, 
	input_tokens INTEGER NOT NULL, 
	output_tokens INTEGER NOT NULL, 
	total_tokens INTEGER NOT NULL, 
	estimated_cost NUMERIC(10, 4) NOT NULL, 
	duration_ms INTEGER, 
	status VARCHAR(20) NOT NULL, 
	error_message TEXT, 
	log_metadata JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	trace_id VARCHAR(255), 
	trace_url TEXT, 
	PRIMARY KEY (id)
)


;
CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_tenant_id ON public.ai_usage_logs (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_trace_id ON public.ai_usage_logs (trace_id)
;
CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_project_id ON public.ai_usage_logs (project_id)
;

-- ========================================================;

ALTER TABLE public.ai_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ai_usage_logs_tenant_isolation_select ON public.ai_usage_logs;
CREATE POLICY ai_usage_logs_tenant_isolation_select ON public.ai_usage_logs
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS ai_usage_logs_tenant_isolation_insert ON public.ai_usage_logs;
CREATE POLICY ai_usage_logs_tenant_isolation_insert ON public.ai_usage_logs
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS ai_usage_logs_tenant_isolation_update ON public.ai_usage_logs;
CREATE POLICY ai_usage_logs_tenant_isolation_update ON public.ai_usage_logs
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS ai_usage_logs_tenant_isolation_delete ON public.ai_usage_logs;
CREATE POLICY ai_usage_logs_tenant_isolation_delete ON public.ai_usage_logs
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.audit_logs (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	user_id UUID, 
	actor_id UUID, 
	action VARCHAR(100) NOT NULL, 
	resource_type VARCHAR(50) NOT NULL, 
	resource_id UUID, 
	changes JSONB NOT NULL, 
	metadata_json JSONB, 
	ip_address VARCHAR(45), 
	user_agent TEXT, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	timestamp TIMESTAMP WITH TIME ZONE, 
	event_hash VARCHAR(64), 
	previous_hash VARCHAR(64), 
	PRIMARY KEY (id)
)


;
CREATE INDEX IF NOT EXISTS ix_audit_logs_tenant_id ON public.audit_logs (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_id ON public.audit_logs (actor_id)
;
CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON public.audit_logs (user_id)
;

-- ========================================================;

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_logs_tenant_isolation_select ON public.audit_logs;
CREATE POLICY audit_logs_tenant_isolation_select ON public.audit_logs
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS audit_logs_tenant_isolation_insert ON public.audit_logs;
CREATE POLICY audit_logs_tenant_isolation_insert ON public.audit_logs
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS audit_logs_tenant_isolation_update ON public.audit_logs;
CREATE POLICY audit_logs_tenant_isolation_update ON public.audit_logs
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS audit_logs_tenant_isolation_delete ON public.audit_logs;
CREATE POLICY audit_logs_tenant_isolation_delete ON public.audit_logs
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.bom_revisions (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	bom_item_id UUID NOT NULL, 
	revision_number INTEGER NOT NULL, 
	changes_json JSONB NOT NULL, 
	changed_by UUID, 
	change_reason TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()' NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT bom_revisions_item_number_unique UNIQUE (bom_item_id, revision_number), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(bom_item_id) REFERENCES public.procurement_bom_items (id) ON DELETE CASCADE, 
	FOREIGN KEY(changed_by) REFERENCES public.users (id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS idx_bom_revisions_item ON public.bom_revisions (bom_item_id)
;
CREATE INDEX IF NOT EXISTS idx_bom_revisions_created ON public.bom_revisions (created_at)
;

-- ========================================================;

ALTER TABLE public.bom_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bom_revisions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_bom_revisions ON public.bom_revisions;
CREATE POLICY tenant_isolation_bom_revisions ON public.bom_revisions
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

CREATE TABLE IF NOT EXISTS public.knowledge_graph_edges (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	source_node_id UUID NOT NULL, 
	target_node_id UUID NOT NULL, 
	relationship_type VARCHAR(100) NOT NULL, 
	properties JSONB NOT NULL, 
	confidence FLOAT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id),
	CONSTRAINT kg_edges_unique UNIQUE (project_id, source_node_id, target_node_id, relationship_type),
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_edges_relationship_type ON public.knowledge_graph_edges (relationship_type)
;
CREATE INDEX IF NOT EXISTS ix_kg_edges_project ON public.knowledge_graph_edges (project_id)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_edges_project_id ON public.knowledge_graph_edges (project_id)
;
CREATE INDEX IF NOT EXISTS ix_kg_edges_source ON public.knowledge_graph_edges (source_node_id)
;
CREATE INDEX IF NOT EXISTS ix_kg_edges_target ON public.knowledge_graph_edges (target_node_id)
;
CREATE INDEX IF NOT EXISTS ix_kg_edges_rel ON public.knowledge_graph_edges (relationship_type)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_edges_target_node_id ON public.knowledge_graph_edges (target_node_id)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_edges_source_node_id ON public.knowledge_graph_edges (source_node_id)
;

-- ========================================================;

ALTER TABLE public.knowledge_graph_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_graph_edges FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_knowledge_graph_edges ON public.knowledge_graph_edges;
CREATE POLICY tenant_isolation_knowledge_graph_edges ON public.knowledge_graph_edges
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

CREATE TABLE IF NOT EXISTS public.knowledge_graph_nodes (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	entity_type VARCHAR(50) NOT NULL, 
	entity_id UUID NOT NULL, 
	label VARCHAR(255), 
	properties JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT kg_nodes_project_entity_unique UNIQUE (project_id, entity_type, entity_id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS ix_kg_nodes_project ON public.knowledge_graph_nodes (project_id)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_nodes_project_id ON public.knowledge_graph_nodes (project_id)
;
CREATE INDEX IF NOT EXISTS ix_kg_nodes_type ON public.knowledge_graph_nodes (entity_type)
;
CREATE INDEX IF NOT EXISTS ix_kg_nodes_entity ON public.knowledge_graph_nodes (entity_id)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_nodes_entity_id ON public.knowledge_graph_nodes (entity_id)
;
CREATE INDEX IF NOT EXISTS ix_knowledge_graph_nodes_entity_type ON public.knowledge_graph_nodes (entity_type)
;

-- ========================================================;

ALTER TABLE public.knowledge_graph_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_graph_nodes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_knowledge_graph_nodes ON public.knowledge_graph_nodes;
CREATE POLICY tenant_isolation_knowledge_graph_nodes ON public.knowledge_graph_nodes
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

CREATE TABLE IF NOT EXISTS public.procurement_plan_snapshots (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	snapshot_name VARCHAR(255) NOT NULL, 
	snapshot_data JSONB NOT NULL, 
	created_by UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()' NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by) REFERENCES public.users (id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS idx_procurement_snapshots_created ON public.procurement_plan_snapshots (created_at)
;
CREATE INDEX IF NOT EXISTS idx_procurement_snapshots_project ON public.procurement_plan_snapshots (project_id)
;

-- ========================================================;

ALTER TABLE public.procurement_plan_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.procurement_plan_snapshots FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_procurement_plan_snapshots ON public.procurement_plan_snapshots;
CREATE POLICY tenant_isolation_procurement_plan_snapshots ON public.procurement_plan_snapshots
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

CREATE TABLE IF NOT EXISTS public.stakeholder_alerts (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	stakeholder_id UUID NOT NULL, 
	alert_id UUID NOT NULL, 
	notification_sent INTEGER NOT NULL, 
	notification_sent_at TIMESTAMP WITH TIME ZONE, 
	notification_method VARCHAR(50), 
	acknowledged INTEGER NOT NULL, 
	acknowledged_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()' NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(stakeholder_id) REFERENCES public.stakeholders (id) ON DELETE CASCADE, 
	FOREIGN KEY(alert_id) REFERENCES public.alerts (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS idx_stakeholder_alerts_alert ON public.stakeholder_alerts (alert_id)
;
CREATE INDEX IF NOT EXISTS idx_stakeholder_alerts_stakeholder ON public.stakeholder_alerts (stakeholder_id)
;

-- ========================================================;

ALTER TABLE public.stakeholder_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stakeholder_alerts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_stakeholder_alerts ON public.stakeholder_alerts;
CREATE POLICY tenant_isolation_stakeholder_alerts ON public.stakeholder_alerts
    FOR ALL
    USING (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    )
    WITH CHECK (
        project_id IN (
            SELECT id
            FROM public.projects
            WHERE tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid
        )
    );

-- Deferred FKs: knowledge_graph_nodes is created later in this file.
ALTER TABLE public.knowledge_graph_edges
    ADD CONSTRAINT fk_kg_edges_source_node_id
    FOREIGN KEY (source_node_id) REFERENCES public.knowledge_graph_nodes (id) ON DELETE CASCADE;

ALTER TABLE public.knowledge_graph_edges
    ADD CONSTRAINT fk_kg_edges_target_node_id
    FOREIGN KEY (target_node_id) REFERENCES public.knowledge_graph_nodes (id) ON DELETE CASCADE;
