-- =====================================================
-- Migration: 20260529000100_add_evidence_intelligence.sql
-- Date: 2026-05-29
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.evidence_claims (
	claim_id UUID NOT NULL, 
	extraction_run_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	dimension VARCHAR(32) NOT NULL, 
	claim_type VARCHAR(64) NOT NULL, 
	value JSONB NOT NULL, 
	algorithmic_certainty FLOAT NOT NULL, 
	freshness FLOAT NOT NULL, 
	verification_status VARCHAR(32) NOT NULL, 
	verification_trace JSONB NOT NULL, 
	lifecycle_status VARCHAR(32) DEFAULT 'shadow' NOT NULL, 
	locator_quality VARCHAR(32) NOT NULL, 
	page INTEGER, 
	char_start INTEGER, 
	char_end INTEGER, 
	quote TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (claim_id), 
	CONSTRAINT ck_claims_dimension CHECK (dimension IN ('SCOPE','BUDGET','TIME','TECHNICAL','LEGAL','QUALITY')), 
	CONSTRAINT ck_claims_verification_status CHECK (verification_status IN ('verified','uncertain','unsupported','fabrication_suspected')), 
	CONSTRAINT ck_claims_locator_quality CHECK (locator_quality IN ('exact','approximate','missing')), 
	CONSTRAINT ck_claims_lifecycle_status CHECK (lifecycle_status IN ('shadow','active','superseded','discarded')), 
	CONSTRAINT ck_claims_certainty_range CHECK (algorithmic_certainty >= 0 AND algorithmic_certainty <= 1), 
	CONSTRAINT ck_claims_freshness_range CHECK (freshness >= 0 AND freshness <= 1)
)


;
CREATE INDEX IF NOT EXISTS ix_claims_doc_lifecycle ON public.evidence_claims (document_id, lifecycle_status)
;
CREATE INDEX IF NOT EXISTS ix_claims_tenancy_doc_run ON public.evidence_claims (tenant_id, project_id, document_id, extraction_run_id)
;

-- ========================================================;

ALTER TABLE public.evidence_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_claims FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS evidence_claims_tenant_isolation_select ON public.evidence_claims;
CREATE POLICY evidence_claims_tenant_isolation_select ON public.evidence_claims
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_claims_tenant_isolation_insert ON public.evidence_claims;
CREATE POLICY evidence_claims_tenant_isolation_insert ON public.evidence_claims
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_claims_tenant_isolation_update ON public.evidence_claims;
CREATE POLICY evidence_claims_tenant_isolation_update ON public.evidence_claims
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_claims_tenant_isolation_delete ON public.evidence_claims;
CREATE POLICY evidence_claims_tenant_isolation_delete ON public.evidence_claims
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.evidence_extraction_events (
	event_id UUID NOT NULL, 
	extraction_run_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	event_type VARCHAR(32) NOT NULL, 
	dimension VARCHAR(32), 
	claim_type VARCHAR(64), 
	reason VARCHAR(64) NOT NULL, 
	payload_trace JSONB NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (event_id), 
	CONSTRAINT ck_events_event_type CHECK (event_type IN ('processing_error','out_of_scope'))
)


;
CREATE INDEX IF NOT EXISTS ix_events_doc_run ON public.evidence_extraction_events (document_id, extraction_run_id)
;
CREATE INDEX IF NOT EXISTS ix_events_diagnostic ON public.evidence_extraction_events (tenant_id, event_type, reason)
;

-- ========================================================;

ALTER TABLE public.evidence_extraction_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_extraction_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS evidence_extraction_events_tenant_isolation_select ON public.evidence_extraction_events;
CREATE POLICY evidence_extraction_events_tenant_isolation_select ON public.evidence_extraction_events
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_extraction_events_tenant_isolation_insert ON public.evidence_extraction_events;
CREATE POLICY evidence_extraction_events_tenant_isolation_insert ON public.evidence_extraction_events
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_extraction_events_tenant_isolation_update ON public.evidence_extraction_events;
CREATE POLICY evidence_extraction_events_tenant_isolation_update ON public.evidence_extraction_events
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS evidence_extraction_events_tenant_isolation_delete ON public.evidence_extraction_events;
CREATE POLICY evidence_extraction_events_tenant_isolation_delete ON public.evidence_extraction_events
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
