-- =====================================================
-- Migration: 20260401000100_add_clause_embeddings.sql
-- Date: 2026-04-01
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.clause_embeddings (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	clause_id VARCHAR(255) NOT NULL, 
	project_id UUID NOT NULL, 
	document_id UUID, 
	document_type VARCHAR(50) DEFAULT 'other' NOT NULL, 
	text TEXT DEFAULT '' NOT NULL, 
	embedding VECTOR(1536) NOT NULL, 
	category VARCHAR(50) DEFAULT 'SCOPE' NOT NULL, 
	embedding_metadata JSONB DEFAULT '{}' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_clause_embeddings_clause_project UNIQUE (clause_id, project_id)
)


;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_tenant_id ON public.clause_embeddings (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_category ON public.clause_embeddings (category)
;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_document_id ON public.clause_embeddings (document_id)
;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_project_id ON public.clause_embeddings (project_id)
;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_tenant ON public.clause_embeddings (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_clause_embeddings_clause_id ON public.clause_embeddings (clause_id)
;

-- ========================================================;

ALTER TABLE public.clause_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clause_embeddings FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clause_embeddings_tenant_isolation_select ON public.clause_embeddings;
CREATE POLICY clause_embeddings_tenant_isolation_select ON public.clause_embeddings
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clause_embeddings_tenant_isolation_insert ON public.clause_embeddings;
CREATE POLICY clause_embeddings_tenant_isolation_insert ON public.clause_embeddings
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clause_embeddings_tenant_isolation_update ON public.clause_embeddings;
CREATE POLICY clause_embeddings_tenant_isolation_update ON public.clause_embeddings
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS clause_embeddings_tenant_isolation_delete ON public.clause_embeddings;
CREATE POLICY clause_embeddings_tenant_isolation_delete ON public.clause_embeddings
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
