-- =====================================================
-- Migration: 20260405000200_add_dlq_failed_tasks.sql
-- Date: 2026-04-05
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.dlq_failed_tasks (
	id UUID DEFAULT gen_random_uuid() NOT NULL, 
	tenant_id UUID NOT NULL, 
	task_type VARCHAR(100) NOT NULL, 
	document_id UUID, 
	payload_json JSONB NOT NULL, 
	error_message TEXT NOT NULL, 
	error_traceback TEXT, 
	retry_count INTEGER DEFAULT 0 NOT NULL, 
	max_retries INTEGER DEFAULT 3 NOT NULL, 
	status VARCHAR(20) DEFAULT 'pending' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, 
	next_retry_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(document_id) REFERENCES public.documents (id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS idx_dlq_failed_tasks_tenant_status ON public.dlq_failed_tasks (tenant_id, status)
;
CREATE INDEX IF NOT EXISTS idx_dlq_failed_tasks_document_id ON public.dlq_failed_tasks (document_id)
;
CREATE INDEX IF NOT EXISTS idx_dlq_failed_tasks_next_retry ON public.dlq_failed_tasks (next_retry_at) WHERE status = 'pending' OR status = 'retrying'
;

-- ========================================================;

ALTER TABLE public.dlq_failed_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dlq_failed_tasks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dlq_failed_tasks_tenant_isolation_select ON public.dlq_failed_tasks;
CREATE POLICY dlq_failed_tasks_tenant_isolation_select ON public.dlq_failed_tasks
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS dlq_failed_tasks_tenant_isolation_insert ON public.dlq_failed_tasks;
CREATE POLICY dlq_failed_tasks_tenant_isolation_insert ON public.dlq_failed_tasks
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS dlq_failed_tasks_tenant_isolation_update ON public.dlq_failed_tasks;
CREATE POLICY dlq_failed_tasks_tenant_isolation_update ON public.dlq_failed_tasks
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS dlq_failed_tasks_tenant_isolation_delete ON public.dlq_failed_tasks;
CREATE POLICY dlq_failed_tasks_tenant_isolation_delete ON public.dlq_failed_tasks
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
