-- =====================================================
-- Migration: 20260225000100_add_review_items.sql
-- Date: 2026-02-25
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reviewstatus') THEN
        CREATE TYPE reviewstatus AS ENUM (
            'DRAFT',
            'PENDING_REVIEW_REQUIRED',
            'PENDING_REVIEW_CONDITIONAL',
            'APPROVED',
            'REJECTED',
            'ESCALATED',
            'CLOSED'
        );
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'impactlevel') THEN
        CREATE TYPE impactlevel AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.review_items (
	id UUID NOT NULL, 
	item_id UUID NOT NULL, 
	item_type VARCHAR(128) NOT NULL, 
	current_status reviewstatus NOT NULL, 
	confidence FLOAT NOT NULL, 
	impact_level impactlevel NOT NULL, 
	tenant_id UUID NOT NULL, 
	approved_by VARCHAR(256), 
	approved_at TIMESTAMP WITHOUT TIME ZONE, 
	sla_due_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	item_data JSONB NOT NULL, 
	review_metadata JSONB NOT NULL, 
	checkpoint_id VARCHAR(255), 
	thread_id VARCHAR(255), 
	project_id UUID, 
	document_id UUID, 
	review_type VARCHAR(128), 
	review_decision TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(document_id) REFERENCES public.documents (id) ON DELETE CASCADE
)


;
CREATE INDEX IF NOT EXISTS ix_review_items_project_status ON public.review_items (project_id, current_status)
;
CREATE INDEX IF NOT EXISTS ix_review_items_checkpoint_id ON public.review_items (checkpoint_id)
;
CREATE INDEX IF NOT EXISTS ix_review_items_current_status ON public.review_items (current_status)
;
CREATE INDEX IF NOT EXISTS ix_review_items_sla_due ON public.review_items (sla_due_date)
;
CREATE INDEX IF NOT EXISTS ix_review_items_item_id ON public.review_items (item_id)
;
CREATE INDEX IF NOT EXISTS ix_review_items_tenant_id ON public.review_items (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_review_items_thread_id ON public.review_items (thread_id)
;
CREATE INDEX IF NOT EXISTS ix_review_items_tenant_status ON public.review_items (tenant_id, current_status)
;

-- ========================================================;

ALTER TABLE public.review_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_items FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS review_items_tenant_isolation_select ON public.review_items;
CREATE POLICY review_items_tenant_isolation_select ON public.review_items
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS review_items_tenant_isolation_insert ON public.review_items;
CREATE POLICY review_items_tenant_isolation_insert ON public.review_items
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS review_items_tenant_isolation_update ON public.review_items;
CREATE POLICY review_items_tenant_isolation_update ON public.review_items
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS review_items_tenant_isolation_delete ON public.review_items;
CREATE POLICY review_items_tenant_isolation_delete ON public.review_items
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
