-- =====================================================
-- Migration: 20260517000100_add_cookie_consents_and_harden_rls.sql
-- Date: 2026-05-17
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.cookie_consents (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	user_id VARCHAR(255) NOT NULL, 
	version VARCHAR(50) NOT NULL, 
	categories JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_cookie_consent_user_version UNIQUE (tenant_id, user_id, version)
)


;
CREATE INDEX IF NOT EXISTS ix_cookie_consents_tenant_id ON public.cookie_consents (tenant_id)
;

-- ========================================================;

ALTER TABLE public.cookie_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cookie_consents FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cookie_consents_tenant_isolation_select ON public.cookie_consents;
CREATE POLICY cookie_consents_tenant_isolation_select ON public.cookie_consents
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS cookie_consents_tenant_isolation_insert ON public.cookie_consents;
CREATE POLICY cookie_consents_tenant_isolation_insert ON public.cookie_consents
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS cookie_consents_tenant_isolation_update ON public.cookie_consents;
CREATE POLICY cookie_consents_tenant_isolation_update ON public.cookie_consents
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS cookie_consents_tenant_isolation_delete ON public.cookie_consents;
CREATE POLICY cookie_consents_tenant_isolation_delete ON public.cookie_consents
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

-- Hardening documents table RLS (TASK-REV-020)
ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS tenant_id UUID;

UPDATE public.documents d
SET tenant_id = p.tenant_id
FROM public.projects p
WHERE d.project_id = p.id
  AND d.tenant_id IS NULL;

CREATE INDEX IF NOT EXISTS ix_documents_tenant ON public.documents(tenant_id);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view documents in their tenant projects" ON public.documents;
DROP POLICY IF EXISTS "Users can upload documents to their tenant projects" ON public.documents;
DROP POLICY IF EXISTS "Users can update documents in their tenant projects" ON public.documents;
DROP POLICY IF EXISTS "Owners and admins can delete documents" ON public.documents;

DROP POLICY IF EXISTS documents_tenant_isolation_select ON public.documents;
CREATE POLICY documents_tenant_isolation_select ON public.documents
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DROP POLICY IF EXISTS documents_tenant_isolation_insert ON public.documents;
CREATE POLICY documents_tenant_isolation_insert ON public.documents
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DROP POLICY IF EXISTS documents_tenant_isolation_update ON public.documents;
CREATE POLICY documents_tenant_isolation_update ON public.documents
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DROP POLICY IF EXISTS documents_tenant_isolation_delete ON public.documents;
CREATE POLICY documents_tenant_isolation_delete ON public.documents
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
