-- =====================================================
-- Migration: 20260614000100_add_project_events_snapshots_artifacts.sql
-- Date: 2026-06-14
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.document_artifacts (
	artifact_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	document_revision_id UUID, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	payload JSONB NOT NULL, 
	lifecycle_status VARCHAR(20) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL, 
	PRIMARY KEY (artifact_id), 
	CONSTRAINT ck_document_artifacts_lifecycle CHECK (lifecycle_status IN ('active','superseded')), 
	FOREIGN KEY(document_revision_id) REFERENCES public.document_revisions (revision_id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS ix_document_artifacts_tenant_id ON public.document_artifacts (tenant_id)
;
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_artifacts_active_document ON public.document_artifacts (document_id) WHERE lifecycle_status = 'active'
;
CREATE INDEX IF NOT EXISTS ix_document_artifacts_project_lifecycle ON public.document_artifacts (project_id, lifecycle_status)
;

-- ========================================================;

ALTER TABLE public.document_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_artifacts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS document_artifacts_tenant_isolation_select ON public.document_artifacts;
CREATE POLICY document_artifacts_tenant_isolation_select ON public.document_artifacts
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_artifacts_tenant_isolation_insert ON public.document_artifacts;
CREATE POLICY document_artifacts_tenant_isolation_insert ON public.document_artifacts
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_artifacts_tenant_isolation_update ON public.document_artifacts;
CREATE POLICY document_artifacts_tenant_isolation_update ON public.document_artifacts
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_artifacts_tenant_isolation_delete ON public.document_artifacts;
CREATE POLICY document_artifacts_tenant_isolation_delete ON public.document_artifacts
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.project_events (
	event_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	event_type VARCHAR(80) NOT NULL, 
	payload JSONB NOT NULL, 
	actor TEXT, 
	confidence FLOAT, 
	source_revision_id UUID, 
	evidence_refs JSONB NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (event_id), 
	FOREIGN KEY(source_revision_id) REFERENCES public.document_revisions (revision_id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS ix_project_events_project_occurred ON public.project_events (project_id, occurred_at)
;
CREATE INDEX IF NOT EXISTS ix_project_events_tenant_id ON public.project_events (tenant_id)
;

-- ========================================================;

ALTER TABLE public.project_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_events_tenant_isolation_select ON public.project_events;
CREATE POLICY project_events_tenant_isolation_select ON public.project_events
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_events_tenant_isolation_insert ON public.project_events;
CREATE POLICY project_events_tenant_isolation_insert ON public.project_events
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_events_tenant_isolation_update ON public.project_events;
CREATE POLICY project_events_tenant_isolation_update ON public.project_events
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_events_tenant_isolation_delete ON public.project_events;
CREATE POLICY project_events_tenant_isolation_delete ON public.project_events
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.project_snapshots (
	snapshot_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	captured_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	trigger VARCHAR(40) NOT NULL, 
	health_vector JSONB NOT NULL, 
	coherence_subscore FLOAT, 
	counts JSONB NOT NULL, 
	totals JSONB NOT NULL, 
	source_event_id UUID, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (snapshot_id, captured_at), 
	CONSTRAINT ck_project_snapshots_trigger CHECK (trigger IN ('revision_ingested','graph_completed','hitl_correction','scheduled','baseline_changed')), 
	FOREIGN KEY(source_event_id) REFERENCES public.project_events (event_id) ON DELETE SET NULL
)
 PARTITION BY RANGE (captured_at)


;
CREATE INDEX IF NOT EXISTS ix_project_snapshots_project_captured ON public.project_snapshots (project_id, captured_at)
;
CREATE INDEX IF NOT EXISTS ix_project_snapshots_tenant_id ON public.project_snapshots (tenant_id)
;

-- ========================================================;

ALTER TABLE public.project_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_snapshots FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_snapshots_tenant_isolation_select ON public.project_snapshots;
CREATE POLICY project_snapshots_tenant_isolation_select ON public.project_snapshots
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_snapshots_tenant_isolation_insert ON public.project_snapshots;
CREATE POLICY project_snapshots_tenant_isolation_insert ON public.project_snapshots
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_snapshots_tenant_isolation_update ON public.project_snapshots;
CREATE POLICY project_snapshots_tenant_isolation_update ON public.project_snapshots
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_snapshots_tenant_isolation_delete ON public.project_snapshots;
CREATE POLICY project_snapshots_tenant_isolation_delete ON public.project_snapshots
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
