-- =====================================================
-- Migration: 20260613000100_add_project_state_and_revisions.sql
-- Date: 2026-06-13
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.document_revisions (
	revision_id UUID NOT NULL, 
	document_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	rev_no INTEGER NOT NULL, 
	parent_revision_id UUID, 
	blob_hash VARCHAR(64) NOT NULL, 
	blob_key TEXT NOT NULL, 
	valid_from TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (revision_id), 
	CONSTRAINT uq_docrev_document_revno UNIQUE (document_id, rev_no), 
	FOREIGN KEY(document_id) REFERENCES public.documents (id) ON DELETE CASCADE, 
	FOREIGN KEY(parent_revision_id) REFERENCES public.document_revisions (revision_id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS ix_document_revisions_tenant_id ON public.document_revisions (tenant_id)
;

-- ========================================================;

ALTER TABLE public.document_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_revisions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS document_revisions_tenant_isolation_select ON public.document_revisions;
CREATE POLICY document_revisions_tenant_isolation_select ON public.document_revisions
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_revisions_tenant_isolation_insert ON public.document_revisions;
CREATE POLICY document_revisions_tenant_isolation_insert ON public.document_revisions
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_revisions_tenant_isolation_update ON public.document_revisions;
CREATE POLICY document_revisions_tenant_isolation_update ON public.document_revisions
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS document_revisions_tenant_isolation_delete ON public.document_revisions;
CREATE POLICY document_revisions_tenant_isolation_delete ON public.document_revisions
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.project_state_entities (
	entity_id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	entity_type VARCHAR(40) NOT NULL, 
	lifecycle_status VARCHAR(20) NOT NULL, 
	source_revision_id UUID, 
	extraction_run_id UUID, 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (entity_id)
)


;
CREATE INDEX IF NOT EXISTS ix_project_state_entities_project_id ON public.project_state_entities (project_id)
;
CREATE INDEX IF NOT EXISTS ix_project_state_entities_tenant_id ON public.project_state_entities (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_project_state_entities_extraction_run_id ON public.project_state_entities (extraction_run_id)
;

-- ========================================================;

ALTER TABLE public.project_state_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_state_entities FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_state_entities_tenant_isolation_select ON public.project_state_entities;
CREATE POLICY project_state_entities_tenant_isolation_select ON public.project_state_entities
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_state_entities_tenant_isolation_insert ON public.project_state_entities;
CREATE POLICY project_state_entities_tenant_isolation_insert ON public.project_state_entities
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_state_entities_tenant_isolation_update ON public.project_state_entities;
CREATE POLICY project_state_entities_tenant_isolation_update ON public.project_state_entities
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_state_entities_tenant_isolation_delete ON public.project_state_entities;
CREATE POLICY project_state_entities_tenant_isolation_delete ON public.project_state_entities
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

CREATE TABLE IF NOT EXISTS public.project_states (
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	lifecycle_status VARCHAR(20) NOT NULL, 
	document_revision_ids JSONB NOT NULL, 
	procurement_refs JSONB NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (project_id)
)


;
CREATE INDEX IF NOT EXISTS ix_project_states_tenant_id ON public.project_states (tenant_id)
;

-- ========================================================;

ALTER TABLE public.project_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_states FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS project_states_tenant_isolation_select ON public.project_states;
CREATE POLICY project_states_tenant_isolation_select ON public.project_states
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_states_tenant_isolation_insert ON public.project_states;
CREATE POLICY project_states_tenant_isolation_insert ON public.project_states
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_states_tenant_isolation_update ON public.project_states;
CREATE POLICY project_states_tenant_isolation_update ON public.project_states
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS project_states_tenant_isolation_delete ON public.project_states;
CREATE POLICY project_states_tenant_isolation_delete ON public.project_states
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

-- Deferred FK: project_states is created later in this file.
ALTER TABLE public.project_state_entities
    ADD CONSTRAINT fk_project_state_entities_project_id
    FOREIGN KEY (project_id) REFERENCES public.project_states (project_id) ON DELETE CASCADE;
