-- =====================================================
-- Migration: 20260406000100_add_wbs_nodes_and_configs.sql
-- Date: 2026-04-06
-- Notes: Autogenerated backfill for TASK-BCK-091
-- =====================================================

CREATE TABLE IF NOT EXISTS public.notification_configs (
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	notification_channels JSONB NOT NULL, 
	email_recipients JSONB, 
	slack_webhook_url TEXT, 
	webhook_url TEXT, 
	webhook_auth_token TEXT, 
	custom_headers JSONB, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
)


;
CREATE UNIQUE INDEX IF NOT EXISTS ix_notification_configs_tenant_id ON public.notification_configs (tenant_id)
;

-- ========================================================;

ALTER TABLE public.notification_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_configs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notification_configs_tenant_isolation_select ON public.notification_configs;
CREATE POLICY notification_configs_tenant_isolation_select ON public.notification_configs
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS notification_configs_tenant_isolation_insert ON public.notification_configs;
CREATE POLICY notification_configs_tenant_isolation_insert ON public.notification_configs
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS notification_configs_tenant_isolation_update ON public.notification_configs;
CREATE POLICY notification_configs_tenant_isolation_update ON public.notification_configs
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS notification_configs_tenant_isolation_delete ON public.notification_configs;
CREATE POLICY notification_configs_tenant_isolation_delete ON public.notification_configs
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'wbsnodetype') THEN
        CREATE TYPE wbsnodetype AS ENUM ('deliverable', 'work_package', 'activity', 'milestone');
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'wbsnodestatus') THEN
        CREATE TYPE wbsnodestatus AS ENUM ('not_started', 'in_progress', 'completed', 'on_hold', 'cancelled');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.wbs_nodes (
	id UUID NOT NULL, 
	project_id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	parent_id UUID, 
	code VARCHAR(50) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	lft INTEGER NOT NULL, 
	rgt INTEGER NOT NULL, 
	depth INTEGER DEFAULT '0' NOT NULL, 
	node_type wbsnodetype DEFAULT 'work_package' NOT NULL, 
	status wbsnodestatus DEFAULT 'not_started' NOT NULL, 
	planned_start TIMESTAMP WITH TIME ZONE, 
	planned_end TIMESTAMP WITH TIME ZONE, 
	actual_start TIMESTAMP WITH TIME ZONE, 
	actual_end TIMESTAMP WITH TIME ZONE, 
	budget_allocated NUMERIC(12, 2), 
	budget_spent NUMERIC(12, 2) DEFAULT '0' NOT NULL, 
	metadata JSONB DEFAULT '{}' NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_wbs_nodes_project_code UNIQUE (project_id, code), 
	CONSTRAINT ck_wbs_nodes_lft_lt_rgt CHECK (lft < rgt), 
	CONSTRAINT ck_wbs_nodes_lft_positive CHECK (lft > 0), 
	CONSTRAINT ck_wbs_nodes_depth_non_negative CHECK (depth >= 0), 
	CONSTRAINT ck_wbs_nodes_budget_spent_non_negative CHECK (budget_spent >= 0), 
	FOREIGN KEY(project_id) REFERENCES public.projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(tenant_id) REFERENCES public.tenants (id) ON DELETE CASCADE, 
	FOREIGN KEY(parent_id) REFERENCES public.wbs_nodes (id) ON DELETE SET NULL
)


;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_parent_id ON public.wbs_nodes (parent_id)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_project_lft_rgt ON public.wbs_nodes (project_id, lft, rgt)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_tenant_id ON public.wbs_nodes (tenant_id)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_status ON public.wbs_nodes (status)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_lft ON public.wbs_nodes (lft)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_rgt ON public.wbs_nodes (rgt)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_depth ON public.wbs_nodes (depth)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_project_id ON public.wbs_nodes (project_id)
;
CREATE INDEX IF NOT EXISTS ix_wbs_nodes_node_type ON public.wbs_nodes (node_type)
;;

ALTER TABLE public.wbs_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wbs_nodes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS wbs_nodes_tenant_isolation_select ON public.wbs_nodes;
CREATE POLICY wbs_nodes_tenant_isolation_select ON public.wbs_nodes
    FOR SELECT
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS wbs_nodes_tenant_isolation_insert ON public.wbs_nodes;
CREATE POLICY wbs_nodes_tenant_isolation_insert ON public.wbs_nodes
    FOR INSERT
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS wbs_nodes_tenant_isolation_update ON public.wbs_nodes;
CREATE POLICY wbs_nodes_tenant_isolation_update ON public.wbs_nodes
    FOR UPDATE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
DROP POLICY IF EXISTS wbs_nodes_tenant_isolation_delete ON public.wbs_nodes;
CREATE POLICY wbs_nodes_tenant_isolation_delete ON public.wbs_nodes
    FOR DELETE
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);
