#!/bin/bash
# CE-20: Pre-Migration Environment Validation
# Validates staging environment readiness before migration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_DIR="$PROJECT_ROOT/logs"
BACKUP_DIR="$PROJECT_ROOT/backups"
DOCS_DIR="$PROJECT_ROOT/docs"

# Create directories if they don't exist
mkdir -p "$LOG_DIR"
mkdir -p "$BACKUP_DIR"
mkdir -p "$DOCS_DIR"

echo "=================================="
echo "CE-20: Environment Validation"
echo "=================================="
echo "Started at: $(date)"
echo

# Load environment variables
if [ -f "$PROJECT_ROOT/.env.staging" ]; then
    source "$PROJECT_ROOT/.env.staging"
    echo "✓ Loaded .env.staging"
else
    echo "⚠ .env.staging not found, using .env"
    source "$PROJECT_ROOT/.env"
fi

# 1. Database Connection Validation
echo
echo "--- Step 1: Database Connection Validation ---"
if python "$PROJECT_ROOT/infrastructure/supabase/check_env.py" --env staging > "$LOG_DIR/ce20_env_check.log" 2>&1; then
    echo "✓ Environment variables validated"
    cat "$LOG_DIR/ce20_env_check.log"
else
    echo "✗ Environment validation failed"
    cat "$LOG_DIR/ce20_env_check.log"
    exit 1
fi

# 2. Check current schema version
echo
echo "--- Step 2: Check Current Schema Version ---"
if [ -n "$DATABASE_URL" ]; then
    psql "$DATABASE_URL" -c "SELECT * FROM alembic_version;" 2>&1 | tee -a "$LOG_DIR/ce20_schema_version.log"
    echo "✓ Schema version captured"
else
    echo "✗ DATABASE_URL not set"
    exit 1
fi

# 3. Capture current state
echo
echo "--- Step 3: Capture Current Database State ---"
if psql "$DATABASE_URL" -f "$SCRIPT_DIR/capture_db_state.sql" > "$LOG_DIR/ce20_pre_state.log" 2>&1; then
    echo "✓ Database state captured"
else
    echo "⚠ Failed to capture full database state (may be expected if tables don't exist yet)"
    cat "$LOG_DIR/ce20_pre_state.log"
fi

# 4. Create pre-migration backup
echo
echo "--- Step 4: Create Pre-Migration Backup ---"
BACKUP_FILE="$BACKUP_DIR/staging_pre_migration_$(date +%Y%m%d_%H%M%S).dump"
echo "Creating backup: $BACKUP_FILE"

# Extract connection details from DATABASE_URL
DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:]*\):.*/\1/p')
DB_PORT=$(echo "$DATABASE_URL" | sed -n 's/.*:\([0-9]*\)\/.*/\1/p')
DB_NAME=$(echo "$DATABASE_URL" | sed -n 's/.*\/\([^?]*\).*/\1/p')
DB_USER=$(echo "$DATABASE_URL" | sed -n 's/.*:\/\/\([^:]*\):.*/\1/p')

if [ -n "$DB_HOST" ] && [ -n "$DB_NAME" ]; then
    if pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
        -F c -b -v -f "$BACKUP_FILE" 2>&1 | tee -a "$LOG_DIR/ce20_backup.log"; then
        BACKUP_SIZE=$(ls -lh "$BACKUP_FILE" | awk '{print $5}')
        echo "✓ Backup created: $BACKUP_FILE ($BACKUP_SIZE)"
    else
        echo "✗ Backup creation failed"
        exit 1
    fi
else
    echo "⚠ Could not parse DATABASE_URL, skipping backup"
fi

# 5. Generate validation report
echo
echo "--- Step 5: Generate Validation Report ---"
cat > "$DOCS_DIR/staging_pre_migration_state.md" << EOF
# Staging Pre-Migration State Report
**Date**: $(date)
**Task**: CE-20 Environment Validation

## Environment Status
✓ Environment variables validated
✓ Database connection successful
✓ Current state captured

## Database Details
- Backup Location: \`$BACKUP_FILE\`
- Backup Size: $BACKUP_SIZE
- State Log: \`$LOG_DIR/ce20_pre_state.log\`

## Schema Version
See: \`$LOG_DIR/ce20_schema_version.log\`

## Next Steps
- Proceed to CE-21: Migration Script Preparation
- Review logs in \`$LOG_DIR/ce20_*.log\`

---
Generated by CE-20 validation script
EOF

echo "✓ Validation report generated: $DOCS_DIR/staging_pre_migration_state.md"

# Summary
echo
echo "=================================="
echo "CE-20 Validation Complete!"
echo "=================================="
echo
echo "Deliverables:"
echo "  ✓ Pre-migration backup: $BACKUP_FILE"
echo "  ✓ State documentation: $DOCS_DIR/staging_pre_migration_state.md"
echo "  ✓ Validation logs: $LOG_DIR/ce20_*.log"
echo
echo "Status: READY FOR CE-21"
echo "Completed at: $(date)"
